/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type PipelinesAPI interface {

	/*
	V1CreatePipeline POST /v1/pipelines

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return PipelinesAPIV1CreatePipelineRequest
	*/
	V1CreatePipeline(ctx context.Context) PipelinesAPIV1CreatePipelineRequest

	// V1CreatePipelineExecute executes the request
	//  @return PipelineView
	V1CreatePipelineExecute(r PipelinesAPIV1CreatePipelineRequest) (*PipelineView, *http.Response, error)

	/*
	V1DeletePipeline DELETE /v1/pipelines/{pipeline_id}

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1DeletePipelineRequest
	*/
	V1DeletePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1DeletePipelineRequest

	// V1DeletePipelineExecute executes the request
	//  @return DeletePipelineResponse
	V1DeletePipelineExecute(r PipelinesAPIV1DeletePipelineRequest) (*DeletePipelineResponse, *http.Response, error)

	/*
	V1GetPipeline GET /v1/pipelines/{pipeline_id}

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1GetPipelineRequest
	*/
	V1GetPipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1GetPipelineRequest

	// V1GetPipelineExecute executes the request
	//  @return PipelineView
	V1GetPipelineExecute(r PipelinesAPIV1GetPipelineRequest) (*PipelineView, *http.Response, error)

	/*
	V1GetPipelineRun GET /v1/pipelines/{pipeline_id}/runs/{run_id}

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@param runId Pipeline run identifier
	@return PipelinesAPIV1GetPipelineRunRequest
	*/
	V1GetPipelineRun(ctx context.Context, pipelineId int64, runId int64) PipelinesAPIV1GetPipelineRunRequest

	// V1GetPipelineRunExecute executes the request
	//  @return PipelineRunView
	V1GetPipelineRunExecute(r PipelinesAPIV1GetPipelineRunRequest) (*PipelineRunView, *http.Response, error)

	/*
	V1ListPipelineRuns GET /v1/pipelines/{pipeline_id}/runs

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1ListPipelineRunsRequest
	*/
	V1ListPipelineRuns(ctx context.Context, pipelineId int64) PipelinesAPIV1ListPipelineRunsRequest

	// V1ListPipelineRunsExecute executes the request
	//  @return ListPipelineRunsResponse
	V1ListPipelineRunsExecute(r PipelinesAPIV1ListPipelineRunsRequest) (*ListPipelineRunsResponse, *http.Response, error)

	/*
	V1ListPipelines GET /v1/pipelines

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return PipelinesAPIV1ListPipelinesRequest
	*/
	V1ListPipelines(ctx context.Context) PipelinesAPIV1ListPipelinesRequest

	// V1ListPipelinesExecute executes the request
	//  @return ListPipelinesResponse
	V1ListPipelinesExecute(r PipelinesAPIV1ListPipelinesRequest) (*ListPipelinesResponse, *http.Response, error)

	/*
	V1PausePipeline POST /v1/pipelines/{pipeline_id}/pause

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1PausePipelineRequest
	*/
	V1PausePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1PausePipelineRequest

	// V1PausePipelineExecute executes the request
	//  @return PipelineView
	V1PausePipelineExecute(r PipelinesAPIV1PausePipelineRequest) (*PipelineView, *http.Response, error)

	/*
	V1ResumePipeline POST /v1/pipelines/{pipeline_id}/resume

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1ResumePipelineRequest
	*/
	V1ResumePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1ResumePipelineRequest

	// V1ResumePipelineExecute executes the request
	//  @return PipelineView
	V1ResumePipelineExecute(r PipelinesAPIV1ResumePipelineRequest) (*PipelineView, *http.Response, error)

	/*
	V1TriggerPipeline POST /v1/pipelines/{pipeline_id}/trigger

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1TriggerPipelineRequest
	*/
	V1TriggerPipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1TriggerPipelineRequest

	// V1TriggerPipelineExecute executes the request
	//  @return TriggerPipelineResponse
	V1TriggerPipelineExecute(r PipelinesAPIV1TriggerPipelineRequest) (*TriggerPipelineResponse, *http.Response, error)

	/*
	V1UpdatePipeline PATCH /v1/pipelines/{pipeline_id}

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param pipelineId Pipeline identifier
	@return PipelinesAPIV1UpdatePipelineRequest
	*/
	V1UpdatePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1UpdatePipelineRequest

	// V1UpdatePipelineExecute executes the request
	//  @return PipelineView
	V1UpdatePipelineExecute(r PipelinesAPIV1UpdatePipelineRequest) (*PipelineView, *http.Response, error)
}

// PipelinesAPIService PipelinesAPI service
type PipelinesAPIService service

type PipelinesAPIV1CreatePipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	createPipelineInput *CreatePipelineInput
}

func (r PipelinesAPIV1CreatePipelineRequest) CreatePipelineInput(createPipelineInput CreatePipelineInput) PipelinesAPIV1CreatePipelineRequest {
	r.createPipelineInput = &createPipelineInput
	return r
}

func (r PipelinesAPIV1CreatePipelineRequest) Execute() (*PipelineView, *http.Response, error) {
	return r.ApiService.V1CreatePipelineExecute(r)
}

/*
V1CreatePipeline POST /v1/pipelines

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return PipelinesAPIV1CreatePipelineRequest
*/
func (a *PipelinesAPIService) V1CreatePipeline(ctx context.Context) PipelinesAPIV1CreatePipelineRequest {
	return PipelinesAPIV1CreatePipelineRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PipelineView
func (a *PipelinesAPIService) V1CreatePipelineExecute(r PipelinesAPIV1CreatePipelineRequest) (*PipelineView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1CreatePipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createPipelineInput == nil {
		return localVarReturnValue, nil, reportError("createPipelineInput is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createPipelineInput
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1DeletePipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
}

func (r PipelinesAPIV1DeletePipelineRequest) Execute() (*DeletePipelineResponse, *http.Response, error) {
	return r.ApiService.V1DeletePipelineExecute(r)
}

/*
V1DeletePipeline DELETE /v1/pipelines/{pipeline_id}

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1DeletePipelineRequest
*/
func (a *PipelinesAPIService) V1DeletePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1DeletePipelineRequest {
	return PipelinesAPIV1DeletePipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return DeletePipelineResponse
func (a *PipelinesAPIService) V1DeletePipelineExecute(r PipelinesAPIV1DeletePipelineRequest) (*DeletePipelineResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *DeletePipelineResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1DeletePipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1GetPipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
}

func (r PipelinesAPIV1GetPipelineRequest) Execute() (*PipelineView, *http.Response, error) {
	return r.ApiService.V1GetPipelineExecute(r)
}

/*
V1GetPipeline GET /v1/pipelines/{pipeline_id}

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1GetPipelineRequest
*/
func (a *PipelinesAPIService) V1GetPipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1GetPipelineRequest {
	return PipelinesAPIV1GetPipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return PipelineView
func (a *PipelinesAPIService) V1GetPipelineExecute(r PipelinesAPIV1GetPipelineRequest) (*PipelineView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1GetPipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1GetPipelineRunRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
	runId int64
}

func (r PipelinesAPIV1GetPipelineRunRequest) Execute() (*PipelineRunView, *http.Response, error) {
	return r.ApiService.V1GetPipelineRunExecute(r)
}

/*
V1GetPipelineRun GET /v1/pipelines/{pipeline_id}/runs/{run_id}

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @param runId Pipeline run identifier
 @return PipelinesAPIV1GetPipelineRunRequest
*/
func (a *PipelinesAPIService) V1GetPipelineRun(ctx context.Context, pipelineId int64, runId int64) PipelinesAPIV1GetPipelineRunRequest {
	return PipelinesAPIV1GetPipelineRunRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
		runId: runId,
	}
}

// Execute executes the request
//  @return PipelineRunView
func (a *PipelinesAPIService) V1GetPipelineRunExecute(r PipelinesAPIV1GetPipelineRunRequest) (*PipelineRunView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineRunView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1GetPipelineRun")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}/runs/{run_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"run_id"+"}", url.PathEscape(parameterValueToString(r.runId, "runId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1ListPipelineRunsRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
	limit *int64
	offset *int64
}

func (r PipelinesAPIV1ListPipelineRunsRequest) Limit(limit int64) PipelinesAPIV1ListPipelineRunsRequest {
	r.limit = &limit
	return r
}

func (r PipelinesAPIV1ListPipelineRunsRequest) Offset(offset int64) PipelinesAPIV1ListPipelineRunsRequest {
	r.offset = &offset
	return r
}

func (r PipelinesAPIV1ListPipelineRunsRequest) Execute() (*ListPipelineRunsResponse, *http.Response, error) {
	return r.ApiService.V1ListPipelineRunsExecute(r)
}

/*
V1ListPipelineRuns GET /v1/pipelines/{pipeline_id}/runs

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1ListPipelineRunsRequest
*/
func (a *PipelinesAPIService) V1ListPipelineRuns(ctx context.Context, pipelineId int64) PipelinesAPIV1ListPipelineRunsRequest {
	return PipelinesAPIV1ListPipelineRunsRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return ListPipelineRunsResponse
func (a *PipelinesAPIService) V1ListPipelineRunsExecute(r PipelinesAPIV1ListPipelineRunsRequest) (*ListPipelineRunsResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListPipelineRunsResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1ListPipelineRuns")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}/runs"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1ListPipelinesRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	status *string
	limit *int64
	offset *int64
}

func (r PipelinesAPIV1ListPipelinesRequest) Status(status string) PipelinesAPIV1ListPipelinesRequest {
	r.status = &status
	return r
}

func (r PipelinesAPIV1ListPipelinesRequest) Limit(limit int64) PipelinesAPIV1ListPipelinesRequest {
	r.limit = &limit
	return r
}

func (r PipelinesAPIV1ListPipelinesRequest) Offset(offset int64) PipelinesAPIV1ListPipelinesRequest {
	r.offset = &offset
	return r
}

func (r PipelinesAPIV1ListPipelinesRequest) Execute() (*ListPipelinesResponse, *http.Response, error) {
	return r.ApiService.V1ListPipelinesExecute(r)
}

/*
V1ListPipelines GET /v1/pipelines

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return PipelinesAPIV1ListPipelinesRequest
*/
func (a *PipelinesAPIService) V1ListPipelines(ctx context.Context) PipelinesAPIV1ListPipelinesRequest {
	return PipelinesAPIV1ListPipelinesRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return ListPipelinesResponse
func (a *PipelinesAPIService) V1ListPipelinesExecute(r PipelinesAPIV1ListPipelinesRequest) (*ListPipelinesResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *ListPipelinesResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1ListPipelines")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.status != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", r.status, "form", "")
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	}
	if r.offset != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "offset", r.offset, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1PausePipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
}

func (r PipelinesAPIV1PausePipelineRequest) Execute() (*PipelineView, *http.Response, error) {
	return r.ApiService.V1PausePipelineExecute(r)
}

/*
V1PausePipeline POST /v1/pipelines/{pipeline_id}/pause

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1PausePipelineRequest
*/
func (a *PipelinesAPIService) V1PausePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1PausePipelineRequest {
	return PipelinesAPIV1PausePipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return PipelineView
func (a *PipelinesAPIService) V1PausePipelineExecute(r PipelinesAPIV1PausePipelineRequest) (*PipelineView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1PausePipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}/pause"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1ResumePipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
}

func (r PipelinesAPIV1ResumePipelineRequest) Execute() (*PipelineView, *http.Response, error) {
	return r.ApiService.V1ResumePipelineExecute(r)
}

/*
V1ResumePipeline POST /v1/pipelines/{pipeline_id}/resume

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1ResumePipelineRequest
*/
func (a *PipelinesAPIService) V1ResumePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1ResumePipelineRequest {
	return PipelinesAPIV1ResumePipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return PipelineView
func (a *PipelinesAPIService) V1ResumePipelineExecute(r PipelinesAPIV1ResumePipelineRequest) (*PipelineView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1ResumePipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}/resume"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1TriggerPipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
	triggerPipelineInput *TriggerPipelineInput
}

func (r PipelinesAPIV1TriggerPipelineRequest) TriggerPipelineInput(triggerPipelineInput TriggerPipelineInput) PipelinesAPIV1TriggerPipelineRequest {
	r.triggerPipelineInput = &triggerPipelineInput
	return r
}

func (r PipelinesAPIV1TriggerPipelineRequest) Execute() (*TriggerPipelineResponse, *http.Response, error) {
	return r.ApiService.V1TriggerPipelineExecute(r)
}

/*
V1TriggerPipeline POST /v1/pipelines/{pipeline_id}/trigger

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1TriggerPipelineRequest
*/
func (a *PipelinesAPIService) V1TriggerPipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1TriggerPipelineRequest {
	return PipelinesAPIV1TriggerPipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return TriggerPipelineResponse
func (a *PipelinesAPIService) V1TriggerPipelineExecute(r PipelinesAPIV1TriggerPipelineRequest) (*TriggerPipelineResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TriggerPipelineResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1TriggerPipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}/trigger"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.triggerPipelineInput == nil {
		return localVarReturnValue, nil, reportError("triggerPipelineInput is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.triggerPipelineInput
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type PipelinesAPIV1UpdatePipelineRequest struct {
	ctx context.Context
	ApiService PipelinesAPI
	pipelineId int64
	updatePipelineInput *UpdatePipelineInput
}

func (r PipelinesAPIV1UpdatePipelineRequest) UpdatePipelineInput(updatePipelineInput UpdatePipelineInput) PipelinesAPIV1UpdatePipelineRequest {
	r.updatePipelineInput = &updatePipelineInput
	return r
}

func (r PipelinesAPIV1UpdatePipelineRequest) Execute() (*PipelineView, *http.Response, error) {
	return r.ApiService.V1UpdatePipelineExecute(r)
}

/*
V1UpdatePipeline PATCH /v1/pipelines/{pipeline_id}

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param pipelineId Pipeline identifier
 @return PipelinesAPIV1UpdatePipelineRequest
*/
func (a *PipelinesAPIService) V1UpdatePipeline(ctx context.Context, pipelineId int64) PipelinesAPIV1UpdatePipelineRequest {
	return PipelinesAPIV1UpdatePipelineRequest{
		ApiService: a,
		ctx: ctx,
		pipelineId: pipelineId,
	}
}

// Execute executes the request
//  @return PipelineView
func (a *PipelinesAPIService) V1UpdatePipelineExecute(r PipelinesAPIV1UpdatePipelineRequest) (*PipelineView, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PipelineView
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PipelinesAPIService.V1UpdatePipeline")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/pipelines/{pipeline_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"pipeline_id"+"}", url.PathEscape(parameterValueToString(r.pipelineId, "pipelineId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updatePipelineInput == nil {
		return localVarReturnValue, nil, reportError("updatePipelineInput is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updatePipelineInput
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Authorization"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
