/*
Reacher

### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.

API version: 4.3.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"time"
)

// checks if the HistoryEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HistoryEntry{}

// HistoryEntry struct for HistoryEntry
type HistoryEntry struct {
	Category NullableString `json:"category,omitempty"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	IsReachable NullableString `json:"is_reachable,omitempty"`
	JobId NullableInt32 `json:"job_id,omitempty"`
	PolicyDecision NullableString `json:"policy_decision,omitempty"`
	PolicyEvaluation interface{} `json:"policy_evaluation,omitempty"`
	PolicyMode NullableString `json:"policy_mode,omitempty"`
	ReasonCodes []string `json:"reason_codes,omitempty"`
	Recommendation interface{} `json:"recommendation,omitempty"`
	RecommendationAction NullableString `json:"recommendation_action,omitempty"`
	SafeToSend NullableBool `json:"safe_to_send,omitempty"`
	Score NullableInt32 `json:"score,omitempty"`
	SubReason NullableString `json:"sub_reason,omitempty"`
}

// NewHistoryEntry instantiates a new HistoryEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHistoryEntry() *HistoryEntry {
	this := HistoryEntry{}
	return &this
}

// NewHistoryEntryWithDefaults instantiates a new HistoryEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHistoryEntryWithDefaults() *HistoryEntry {
	this := HistoryEntry{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetCategory() string {
	if o == nil || IsNil(o.Category.Get()) {
		var ret string
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *HistoryEntry) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableString and assigns it to the Category field.
func (o *HistoryEntry) SetCategory(v string) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *HistoryEntry) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *HistoryEntry) UnsetCategory() {
	o.Category.Unset()
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *HistoryEntry) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *HistoryEntry) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *HistoryEntry) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *HistoryEntry) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetIsReachable returns the IsReachable field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetIsReachable() string {
	if o == nil || IsNil(o.IsReachable.Get()) {
		var ret string
		return ret
	}
	return *o.IsReachable.Get()
}

// GetIsReachableOk returns a tuple with the IsReachable field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetIsReachableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsReachable.Get(), o.IsReachable.IsSet()
}

// HasIsReachable returns a boolean if a field has been set.
func (o *HistoryEntry) HasIsReachable() bool {
	if o != nil && o.IsReachable.IsSet() {
		return true
	}

	return false
}

// SetIsReachable gets a reference to the given NullableString and assigns it to the IsReachable field.
func (o *HistoryEntry) SetIsReachable(v string) {
	o.IsReachable.Set(&v)
}
// SetIsReachableNil sets the value for IsReachable to be an explicit nil
func (o *HistoryEntry) SetIsReachableNil() {
	o.IsReachable.Set(nil)
}

// UnsetIsReachable ensures that no value is present for IsReachable, not even an explicit nil
func (o *HistoryEntry) UnsetIsReachable() {
	o.IsReachable.Unset()
}

// GetJobId returns the JobId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetJobId() int32 {
	if o == nil || IsNil(o.JobId.Get()) {
		var ret int32
		return ret
	}
	return *o.JobId.Get()
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetJobIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.JobId.Get(), o.JobId.IsSet()
}

// HasJobId returns a boolean if a field has been set.
func (o *HistoryEntry) HasJobId() bool {
	if o != nil && o.JobId.IsSet() {
		return true
	}

	return false
}

// SetJobId gets a reference to the given NullableInt32 and assigns it to the JobId field.
func (o *HistoryEntry) SetJobId(v int32) {
	o.JobId.Set(&v)
}
// SetJobIdNil sets the value for JobId to be an explicit nil
func (o *HistoryEntry) SetJobIdNil() {
	o.JobId.Set(nil)
}

// UnsetJobId ensures that no value is present for JobId, not even an explicit nil
func (o *HistoryEntry) UnsetJobId() {
	o.JobId.Unset()
}

// GetPolicyDecision returns the PolicyDecision field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetPolicyDecision() string {
	if o == nil || IsNil(o.PolicyDecision.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyDecision.Get()
}

// GetPolicyDecisionOk returns a tuple with the PolicyDecision field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetPolicyDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyDecision.Get(), o.PolicyDecision.IsSet()
}

// HasPolicyDecision returns a boolean if a field has been set.
func (o *HistoryEntry) HasPolicyDecision() bool {
	if o != nil && o.PolicyDecision.IsSet() {
		return true
	}

	return false
}

// SetPolicyDecision gets a reference to the given NullableString and assigns it to the PolicyDecision field.
func (o *HistoryEntry) SetPolicyDecision(v string) {
	o.PolicyDecision.Set(&v)
}
// SetPolicyDecisionNil sets the value for PolicyDecision to be an explicit nil
func (o *HistoryEntry) SetPolicyDecisionNil() {
	o.PolicyDecision.Set(nil)
}

// UnsetPolicyDecision ensures that no value is present for PolicyDecision, not even an explicit nil
func (o *HistoryEntry) UnsetPolicyDecision() {
	o.PolicyDecision.Unset()
}

// GetPolicyEvaluation returns the PolicyEvaluation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetPolicyEvaluation() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PolicyEvaluation
}

// GetPolicyEvaluationOk returns a tuple with the PolicyEvaluation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetPolicyEvaluationOk() (*interface{}, bool) {
	if o == nil || IsNil(o.PolicyEvaluation) {
		return nil, false
	}
	return &o.PolicyEvaluation, true
}

// HasPolicyEvaluation returns a boolean if a field has been set.
func (o *HistoryEntry) HasPolicyEvaluation() bool {
	if o != nil && !IsNil(o.PolicyEvaluation) {
		return true
	}

	return false
}

// SetPolicyEvaluation gets a reference to the given interface{} and assigns it to the PolicyEvaluation field.
func (o *HistoryEntry) SetPolicyEvaluation(v interface{}) {
	o.PolicyEvaluation = v
}

// GetPolicyMode returns the PolicyMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetPolicyMode() string {
	if o == nil || IsNil(o.PolicyMode.Get()) {
		var ret string
		return ret
	}
	return *o.PolicyMode.Get()
}

// GetPolicyModeOk returns a tuple with the PolicyMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetPolicyModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyMode.Get(), o.PolicyMode.IsSet()
}

// HasPolicyMode returns a boolean if a field has been set.
func (o *HistoryEntry) HasPolicyMode() bool {
	if o != nil && o.PolicyMode.IsSet() {
		return true
	}

	return false
}

// SetPolicyMode gets a reference to the given NullableString and assigns it to the PolicyMode field.
func (o *HistoryEntry) SetPolicyMode(v string) {
	o.PolicyMode.Set(&v)
}
// SetPolicyModeNil sets the value for PolicyMode to be an explicit nil
func (o *HistoryEntry) SetPolicyModeNil() {
	o.PolicyMode.Set(nil)
}

// UnsetPolicyMode ensures that no value is present for PolicyMode, not even an explicit nil
func (o *HistoryEntry) UnsetPolicyMode() {
	o.PolicyMode.Unset()
}

// GetReasonCodes returns the ReasonCodes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetReasonCodes() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ReasonCodes
}

// GetReasonCodesOk returns a tuple with the ReasonCodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetReasonCodesOk() ([]string, bool) {
	if o == nil || IsNil(o.ReasonCodes) {
		return nil, false
	}
	return o.ReasonCodes, true
}

// HasReasonCodes returns a boolean if a field has been set.
func (o *HistoryEntry) HasReasonCodes() bool {
	if o != nil && !IsNil(o.ReasonCodes) {
		return true
	}

	return false
}

// SetReasonCodes gets a reference to the given []string and assigns it to the ReasonCodes field.
func (o *HistoryEntry) SetReasonCodes(v []string) {
	o.ReasonCodes = v
}

// GetRecommendation returns the Recommendation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetRecommendation() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetRecommendationOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Recommendation) {
		return nil, false
	}
	return &o.Recommendation, true
}

// HasRecommendation returns a boolean if a field has been set.
func (o *HistoryEntry) HasRecommendation() bool {
	if o != nil && !IsNil(o.Recommendation) {
		return true
	}

	return false
}

// SetRecommendation gets a reference to the given interface{} and assigns it to the Recommendation field.
func (o *HistoryEntry) SetRecommendation(v interface{}) {
	o.Recommendation = v
}

// GetRecommendationAction returns the RecommendationAction field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetRecommendationAction() string {
	if o == nil || IsNil(o.RecommendationAction.Get()) {
		var ret string
		return ret
	}
	return *o.RecommendationAction.Get()
}

// GetRecommendationActionOk returns a tuple with the RecommendationAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetRecommendationActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecommendationAction.Get(), o.RecommendationAction.IsSet()
}

// HasRecommendationAction returns a boolean if a field has been set.
func (o *HistoryEntry) HasRecommendationAction() bool {
	if o != nil && o.RecommendationAction.IsSet() {
		return true
	}

	return false
}

// SetRecommendationAction gets a reference to the given NullableString and assigns it to the RecommendationAction field.
func (o *HistoryEntry) SetRecommendationAction(v string) {
	o.RecommendationAction.Set(&v)
}
// SetRecommendationActionNil sets the value for RecommendationAction to be an explicit nil
func (o *HistoryEntry) SetRecommendationActionNil() {
	o.RecommendationAction.Set(nil)
}

// UnsetRecommendationAction ensures that no value is present for RecommendationAction, not even an explicit nil
func (o *HistoryEntry) UnsetRecommendationAction() {
	o.RecommendationAction.Unset()
}

// GetSafeToSend returns the SafeToSend field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetSafeToSend() bool {
	if o == nil || IsNil(o.SafeToSend.Get()) {
		var ret bool
		return ret
	}
	return *o.SafeToSend.Get()
}

// GetSafeToSendOk returns a tuple with the SafeToSend field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetSafeToSendOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SafeToSend.Get(), o.SafeToSend.IsSet()
}

// HasSafeToSend returns a boolean if a field has been set.
func (o *HistoryEntry) HasSafeToSend() bool {
	if o != nil && o.SafeToSend.IsSet() {
		return true
	}

	return false
}

// SetSafeToSend gets a reference to the given NullableBool and assigns it to the SafeToSend field.
func (o *HistoryEntry) SetSafeToSend(v bool) {
	o.SafeToSend.Set(&v)
}
// SetSafeToSendNil sets the value for SafeToSend to be an explicit nil
func (o *HistoryEntry) SetSafeToSendNil() {
	o.SafeToSend.Set(nil)
}

// UnsetSafeToSend ensures that no value is present for SafeToSend, not even an explicit nil
func (o *HistoryEntry) UnsetSafeToSend() {
	o.SafeToSend.Unset()
}

// GetScore returns the Score field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetScore() int32 {
	if o == nil || IsNil(o.Score.Get()) {
		var ret int32
		return ret
	}
	return *o.Score.Get()
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetScoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Score.Get(), o.Score.IsSet()
}

// HasScore returns a boolean if a field has been set.
func (o *HistoryEntry) HasScore() bool {
	if o != nil && o.Score.IsSet() {
		return true
	}

	return false
}

// SetScore gets a reference to the given NullableInt32 and assigns it to the Score field.
func (o *HistoryEntry) SetScore(v int32) {
	o.Score.Set(&v)
}
// SetScoreNil sets the value for Score to be an explicit nil
func (o *HistoryEntry) SetScoreNil() {
	o.Score.Set(nil)
}

// UnsetScore ensures that no value is present for Score, not even an explicit nil
func (o *HistoryEntry) UnsetScore() {
	o.Score.Unset()
}

// GetSubReason returns the SubReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HistoryEntry) GetSubReason() string {
	if o == nil || IsNil(o.SubReason.Get()) {
		var ret string
		return ret
	}
	return *o.SubReason.Get()
}

// GetSubReasonOk returns a tuple with the SubReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HistoryEntry) GetSubReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubReason.Get(), o.SubReason.IsSet()
}

// HasSubReason returns a boolean if a field has been set.
func (o *HistoryEntry) HasSubReason() bool {
	if o != nil && o.SubReason.IsSet() {
		return true
	}

	return false
}

// SetSubReason gets a reference to the given NullableString and assigns it to the SubReason field.
func (o *HistoryEntry) SetSubReason(v string) {
	o.SubReason.Set(&v)
}
// SetSubReasonNil sets the value for SubReason to be an explicit nil
func (o *HistoryEntry) SetSubReasonNil() {
	o.SubReason.Set(nil)
}

// UnsetSubReason ensures that no value is present for SubReason, not even an explicit nil
func (o *HistoryEntry) UnsetSubReason() {
	o.SubReason.Unset()
}

func (o HistoryEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HistoryEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	if o.IsReachable.IsSet() {
		toSerialize["is_reachable"] = o.IsReachable.Get()
	}
	if o.JobId.IsSet() {
		toSerialize["job_id"] = o.JobId.Get()
	}
	if o.PolicyDecision.IsSet() {
		toSerialize["policy_decision"] = o.PolicyDecision.Get()
	}
	if o.PolicyEvaluation != nil {
		toSerialize["policy_evaluation"] = o.PolicyEvaluation
	}
	if o.PolicyMode.IsSet() {
		toSerialize["policy_mode"] = o.PolicyMode.Get()
	}
	if o.ReasonCodes != nil {
		toSerialize["reason_codes"] = o.ReasonCodes
	}
	if o.Recommendation != nil {
		toSerialize["recommendation"] = o.Recommendation
	}
	if o.RecommendationAction.IsSet() {
		toSerialize["recommendation_action"] = o.RecommendationAction.Get()
	}
	if o.SafeToSend.IsSet() {
		toSerialize["safe_to_send"] = o.SafeToSend.Get()
	}
	if o.Score.IsSet() {
		toSerialize["score"] = o.Score.Get()
	}
	if o.SubReason.IsSet() {
		toSerialize["sub_reason"] = o.SubReason.Get()
	}
	return toSerialize, nil
}

type NullableHistoryEntry struct {
	value *HistoryEntry
	isSet bool
}

func (v NullableHistoryEntry) Get() *HistoryEntry {
	return v.value
}

func (v *NullableHistoryEntry) Set(val *HistoryEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableHistoryEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableHistoryEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHistoryEntry(val *HistoryEntry) *NullableHistoryEntry {
	return &NullableHistoryEntry{value: val, isSet: true}
}

func (v NullableHistoryEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHistoryEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
