/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApprovalChecklistResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalChecklistResponse{}

// ApprovalChecklistResponse struct for ApprovalChecklistResponse
type ApprovalChecklistResponse struct {
	Categories ApprovalCategoryBreakdown `json:"categories"`
	JobId int32 `json:"job_id"`
	ReadyToSend bool `json:"ready_to_send"`
	Recommendation string `json:"recommendation"`
	RiskFlags ApprovalRiskFlags `json:"risk_flags"`
	SafeToSendCount int64 `json:"safe_to_send_count"`
	SafeToSendPct float32 `json:"safe_to_send_pct"`
	TotalRecords int32 `json:"total_records"`
}

type _ApprovalChecklistResponse ApprovalChecklistResponse

// NewApprovalChecklistResponse instantiates a new ApprovalChecklistResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalChecklistResponse(categories ApprovalCategoryBreakdown, jobId int32, readyToSend bool, recommendation string, riskFlags ApprovalRiskFlags, safeToSendCount int64, safeToSendPct float32, totalRecords int32) *ApprovalChecklistResponse {
	this := ApprovalChecklistResponse{}
	this.Categories = categories
	this.JobId = jobId
	this.ReadyToSend = readyToSend
	this.Recommendation = recommendation
	this.RiskFlags = riskFlags
	this.SafeToSendCount = safeToSendCount
	this.SafeToSendPct = safeToSendPct
	this.TotalRecords = totalRecords
	return &this
}

// NewApprovalChecklistResponseWithDefaults instantiates a new ApprovalChecklistResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalChecklistResponseWithDefaults() *ApprovalChecklistResponse {
	this := ApprovalChecklistResponse{}
	return &this
}

// GetCategories returns the Categories field value
func (o *ApprovalChecklistResponse) GetCategories() ApprovalCategoryBreakdown {
	if o == nil {
		var ret ApprovalCategoryBreakdown
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetCategoriesOk() (*ApprovalCategoryBreakdown, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Categories, true
}

// SetCategories sets field value
func (o *ApprovalChecklistResponse) SetCategories(v ApprovalCategoryBreakdown) {
	o.Categories = v
}

// GetJobId returns the JobId field value
func (o *ApprovalChecklistResponse) GetJobId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetJobIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *ApprovalChecklistResponse) SetJobId(v int32) {
	o.JobId = v
}

// GetReadyToSend returns the ReadyToSend field value
func (o *ApprovalChecklistResponse) GetReadyToSend() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReadyToSend
}

// GetReadyToSendOk returns a tuple with the ReadyToSend field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetReadyToSendOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadyToSend, true
}

// SetReadyToSend sets field value
func (o *ApprovalChecklistResponse) SetReadyToSend(v bool) {
	o.ReadyToSend = v
}

// GetRecommendation returns the Recommendation field value
func (o *ApprovalChecklistResponse) GetRecommendation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recommendation
}

// GetRecommendationOk returns a tuple with the Recommendation field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetRecommendationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recommendation, true
}

// SetRecommendation sets field value
func (o *ApprovalChecklistResponse) SetRecommendation(v string) {
	o.Recommendation = v
}

// GetRiskFlags returns the RiskFlags field value
func (o *ApprovalChecklistResponse) GetRiskFlags() ApprovalRiskFlags {
	if o == nil {
		var ret ApprovalRiskFlags
		return ret
	}

	return o.RiskFlags
}

// GetRiskFlagsOk returns a tuple with the RiskFlags field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetRiskFlagsOk() (*ApprovalRiskFlags, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskFlags, true
}

// SetRiskFlags sets field value
func (o *ApprovalChecklistResponse) SetRiskFlags(v ApprovalRiskFlags) {
	o.RiskFlags = v
}

// GetSafeToSendCount returns the SafeToSendCount field value
func (o *ApprovalChecklistResponse) GetSafeToSendCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.SafeToSendCount
}

// GetSafeToSendCountOk returns a tuple with the SafeToSendCount field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetSafeToSendCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SafeToSendCount, true
}

// SetSafeToSendCount sets field value
func (o *ApprovalChecklistResponse) SetSafeToSendCount(v int64) {
	o.SafeToSendCount = v
}

// GetSafeToSendPct returns the SafeToSendPct field value
func (o *ApprovalChecklistResponse) GetSafeToSendPct() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SafeToSendPct
}

// GetSafeToSendPctOk returns a tuple with the SafeToSendPct field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetSafeToSendPctOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SafeToSendPct, true
}

// SetSafeToSendPct sets field value
func (o *ApprovalChecklistResponse) SetSafeToSendPct(v float32) {
	o.SafeToSendPct = v
}

// GetTotalRecords returns the TotalRecords field value
func (o *ApprovalChecklistResponse) GetTotalRecords() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalRecords
}

// GetTotalRecordsOk returns a tuple with the TotalRecords field value
// and a boolean to check if the value has been set.
func (o *ApprovalChecklistResponse) GetTotalRecordsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalRecords, true
}

// SetTotalRecords sets field value
func (o *ApprovalChecklistResponse) SetTotalRecords(v int32) {
	o.TotalRecords = v
}

func (o ApprovalChecklistResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalChecklistResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["categories"] = o.Categories
	toSerialize["job_id"] = o.JobId
	toSerialize["ready_to_send"] = o.ReadyToSend
	toSerialize["recommendation"] = o.Recommendation
	toSerialize["risk_flags"] = o.RiskFlags
	toSerialize["safe_to_send_count"] = o.SafeToSendCount
	toSerialize["safe_to_send_pct"] = o.SafeToSendPct
	toSerialize["total_records"] = o.TotalRecords
	return toSerialize, nil
}

func (o *ApprovalChecklistResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"categories",
		"job_id",
		"ready_to_send",
		"recommendation",
		"risk_flags",
		"safe_to_send_count",
		"safe_to_send_pct",
		"total_records",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApprovalChecklistResponse := _ApprovalChecklistResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varApprovalChecklistResponse)

	if err != nil {
		return err
	}

	*o = ApprovalChecklistResponse(varApprovalChecklistResponse)

	return err
}

type NullableApprovalChecklistResponse struct {
	value *ApprovalChecklistResponse
	isSet bool
}

func (v NullableApprovalChecklistResponse) Get() *ApprovalChecklistResponse {
	return v.value
}

func (v *NullableApprovalChecklistResponse) Set(val *ApprovalChecklistResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalChecklistResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalChecklistResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalChecklistResponse(val *ApprovalChecklistResponse) *NullableApprovalChecklistResponse {
	return &NullableApprovalChecklistResponse{value: val, isSet: true}
}

func (v NullableApprovalChecklistResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalChecklistResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


