/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// BounceRiskCategory the model 'BounceRiskCategory'
type BounceRiskCategory string

// List of BounceRiskCategory
const (
	BOUNCERISKCATEGORY_SAFE BounceRiskCategory = "safe"
	BOUNCERISKCATEGORY_LOW BounceRiskCategory = "low"
	BOUNCERISKCATEGORY_MEDIUM BounceRiskCategory = "medium"
	BOUNCERISKCATEGORY_HIGH BounceRiskCategory = "high"
	BOUNCERISKCATEGORY_DANGEROUS BounceRiskCategory = "dangerous"
)

// All allowed values of BounceRiskCategory enum
var AllowedBounceRiskCategoryEnumValues = []BounceRiskCategory{
	"safe",
	"low",
	"medium",
	"high",
	"dangerous",
}

func (v *BounceRiskCategory) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BounceRiskCategory(value)
	for _, existing := range AllowedBounceRiskCategoryEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BounceRiskCategory", value)
}

// NewBounceRiskCategoryFromValue returns a pointer to a valid BounceRiskCategory
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBounceRiskCategoryFromValue(v string) (*BounceRiskCategory, error) {
	ev := BounceRiskCategory(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BounceRiskCategory: valid values are %v", v, AllowedBounceRiskCategoryEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BounceRiskCategory) IsValid() bool {
	for _, existing := range AllowedBounceRiskCategoryEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BounceRiskCategory value
func (v BounceRiskCategory) Ptr() *BounceRiskCategory {
	return &v
}

type NullableBounceRiskCategory struct {
	value *BounceRiskCategory
	isSet bool
}

func (v NullableBounceRiskCategory) Get() *BounceRiskCategory {
	return v.value
}

func (v *NullableBounceRiskCategory) Set(val *BounceRiskCategory) {
	v.value = val
	v.isSet = true
}

func (v NullableBounceRiskCategory) IsSet() bool {
	return v.isSet
}

func (v *NullableBounceRiskCategory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBounceRiskCategory(val *BounceRiskCategory) *NullableBounceRiskCategory {
	return &NullableBounceRiskCategory{value: val, isSet: true}
}

func (v NullableBounceRiskCategory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBounceRiskCategory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

