/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// ProviderRejectionReason the model 'ProviderRejectionReason'
type ProviderRejectionReason string

// List of ProviderRejectionReason
const (
	PROVIDERREJECTIONREASON_PROVIDER_LOCAL_PART_TOO_SHORT ProviderRejectionReason = "provider_local_part_too_short"
	PROVIDERREJECTIONREASON_PROVIDER_LOCAL_PART_TOO_LONG ProviderRejectionReason = "provider_local_part_too_long"
	PROVIDERREJECTIONREASON_PROVIDER_INVALID_CHARACTER ProviderRejectionReason = "provider_invalid_character"
	PROVIDERREJECTIONREASON_PROVIDER_CONSECUTIVE_SPECIAL_CHARACTERS ProviderRejectionReason = "provider_consecutive_special_characters"
	PROVIDERREJECTIONREASON_PROVIDER_INVALID_START_CHARACTER ProviderRejectionReason = "provider_invalid_start_character"
	PROVIDERREJECTIONREASON_PROVIDER_INVALID_END_CHARACTER ProviderRejectionReason = "provider_invalid_end_character"
	PROVIDERREJECTIONREASON_PROVIDER_PLUS_ADDRESSING_NOT_SUPPORTED ProviderRejectionReason = "provider_plus_addressing_not_supported"
	PROVIDERREJECTIONREASON_PROVIDER_RESERVED_WORD ProviderRejectionReason = "provider_reserved_word"
	PROVIDERREJECTIONREASON_PROVIDER_FORMAT_VIOLATION ProviderRejectionReason = "provider_format_violation"
)

// All allowed values of ProviderRejectionReason enum
var AllowedProviderRejectionReasonEnumValues = []ProviderRejectionReason{
	"provider_local_part_too_short",
	"provider_local_part_too_long",
	"provider_invalid_character",
	"provider_consecutive_special_characters",
	"provider_invalid_start_character",
	"provider_invalid_end_character",
	"provider_plus_addressing_not_supported",
	"provider_reserved_word",
	"provider_format_violation",
}

func (v *ProviderRejectionReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ProviderRejectionReason(value)
	for _, existing := range AllowedProviderRejectionReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ProviderRejectionReason", value)
}

// NewProviderRejectionReasonFromValue returns a pointer to a valid ProviderRejectionReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewProviderRejectionReasonFromValue(v string) (*ProviderRejectionReason, error) {
	ev := ProviderRejectionReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ProviderRejectionReason: valid values are %v", v, AllowedProviderRejectionReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ProviderRejectionReason) IsValid() bool {
	for _, existing := range AllowedProviderRejectionReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ProviderRejectionReason value
func (v ProviderRejectionReason) Ptr() *ProviderRejectionReason {
	return &v
}

type NullableProviderRejectionReason struct {
	value *ProviderRejectionReason
	isSet bool
}

func (v NullableProviderRejectionReason) Get() *ProviderRejectionReason {
	return v.value
}

func (v *NullableProviderRejectionReason) Set(val *ProviderRejectionReason) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderRejectionReason) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderRejectionReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderRejectionReason(val *ProviderRejectionReason) *NullableProviderRejectionReason {
	return &NullableProviderRejectionReason{value: val, isSet: true}
}

func (v NullableProviderRejectionReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderRejectionReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

