/*
Reacher

### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.

API version: 4.3.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
)

// checks if the AdminApiKeyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminApiKeyList{}

// AdminApiKeyList struct for AdminApiKeyList
type AdminApiKeyList struct {
	ApiKeys []AdminApiKey `json:"api_keys,omitempty"`
}

// NewAdminApiKeyList instantiates a new AdminApiKeyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminApiKeyList() *AdminApiKeyList {
	this := AdminApiKeyList{}
	return &this
}

// NewAdminApiKeyListWithDefaults instantiates a new AdminApiKeyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminApiKeyListWithDefaults() *AdminApiKeyList {
	this := AdminApiKeyList{}
	return &this
}

// GetApiKeys returns the ApiKeys field value if set, zero value otherwise.
func (o *AdminApiKeyList) GetApiKeys() []AdminApiKey {
	if o == nil || IsNil(o.ApiKeys) {
		var ret []AdminApiKey
		return ret
	}
	return o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdminApiKeyList) GetApiKeysOk() ([]AdminApiKey, bool) {
	if o == nil || IsNil(o.ApiKeys) {
		return nil, false
	}
	return o.ApiKeys, true
}

// HasApiKeys returns a boolean if a field has been set.
func (o *AdminApiKeyList) HasApiKeys() bool {
	if o != nil && !IsNil(o.ApiKeys) {
		return true
	}

	return false
}

// SetApiKeys gets a reference to the given []AdminApiKey and assigns it to the ApiKeys field.
func (o *AdminApiKeyList) SetApiKeys(v []AdminApiKey) {
	o.ApiKeys = v
}

func (o AdminApiKeyList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminApiKeyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiKeys) {
		toSerialize["api_keys"] = o.ApiKeys
	}
	return toSerialize, nil
}

type NullableAdminApiKeyList struct {
	value *AdminApiKeyList
	isSet bool
}

func (v NullableAdminApiKeyList) Get() *AdminApiKeyList {
	return v.value
}

func (v *NullableAdminApiKeyList) Set(val *AdminApiKeyList) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminApiKeyList) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminApiKeyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminApiKeyList(val *AdminApiKeyList) *NullableAdminApiKeyList {
	return &NullableAdminApiKeyList{value: val, isSet: true}
}

func (v NullableAdminApiKeyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminApiKeyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
