/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutcomeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutcomeListResponse{}

// OutcomeListResponse struct for OutcomeListResponse
type OutcomeListResponse struct {
	Outcomes []OutcomeView `json:"outcomes"`
	Total int64 `json:"total"`
}

type _OutcomeListResponse OutcomeListResponse

// NewOutcomeListResponse instantiates a new OutcomeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutcomeListResponse(outcomes []OutcomeView, total int64) *OutcomeListResponse {
	this := OutcomeListResponse{}
	this.Outcomes = outcomes
	this.Total = total
	return &this
}

// NewOutcomeListResponseWithDefaults instantiates a new OutcomeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutcomeListResponseWithDefaults() *OutcomeListResponse {
	this := OutcomeListResponse{}
	return &this
}

// GetOutcomes returns the Outcomes field value
func (o *OutcomeListResponse) GetOutcomes() []OutcomeView {
	if o == nil {
		var ret []OutcomeView
		return ret
	}

	return o.Outcomes
}

// GetOutcomesOk returns a tuple with the Outcomes field value
// and a boolean to check if the value has been set.
func (o *OutcomeListResponse) GetOutcomesOk() ([]OutcomeView, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outcomes, true
}

// SetOutcomes sets field value
func (o *OutcomeListResponse) SetOutcomes(v []OutcomeView) {
	o.Outcomes = v
}

// GetTotal returns the Total field value
func (o *OutcomeListResponse) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *OutcomeListResponse) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *OutcomeListResponse) SetTotal(v int64) {
	o.Total = v
}

func (o OutcomeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutcomeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["outcomes"] = o.Outcomes
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *OutcomeListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"outcomes",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutcomeListResponse := _OutcomeListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varOutcomeListResponse)

	if err != nil {
		return err
	}

	*o = OutcomeListResponse(varOutcomeListResponse)

	return err
}

type NullableOutcomeListResponse struct {
	value *OutcomeListResponse
	isSet bool
}

func (v NullableOutcomeListResponse) Get() *OutcomeListResponse {
	return v.value
}

func (v *NullableOutcomeListResponse) Set(val *OutcomeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOutcomeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOutcomeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutcomeListResponse(val *OutcomeListResponse) *NullableOutcomeListResponse {
	return &NullableOutcomeListResponse{value: val, isSet: true}
}

func (v NullableOutcomeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutcomeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
