/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 4.3.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
)

// checks if the UpdateProviderEndpointInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProviderEndpointInput{}

// UpdateProviderEndpointInput struct for UpdateProviderEndpointInput
type UpdateProviderEndpointInput struct {
	AllowedIps []string `json:"allowed_ips,omitempty"`
	Label NullableString `json:"label,omitempty"`
	ProviderConfig interface{} `json:"provider_config,omitempty"`
	RotateDeliveryToken *bool `json:"rotate_delivery_token,omitempty"`
	Status NullableString `json:"status,omitempty"`
}

// NewUpdateProviderEndpointInput instantiates a new UpdateProviderEndpointInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProviderEndpointInput() *UpdateProviderEndpointInput {
	this := UpdateProviderEndpointInput{}
	return &this
}

// NewUpdateProviderEndpointInputWithDefaults instantiates a new UpdateProviderEndpointInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProviderEndpointInputWithDefaults() *UpdateProviderEndpointInput {
	this := UpdateProviderEndpointInput{}
	return &this
}

// GetAllowedIps returns the AllowedIps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateProviderEndpointInput) GetAllowedIps() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.AllowedIps
}

// GetAllowedIpsOk returns a tuple with the AllowedIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateProviderEndpointInput) GetAllowedIpsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedIps) {
		return nil, false
	}
	return o.AllowedIps, true
}

// HasAllowedIps returns a boolean if a field has been set.
func (o *UpdateProviderEndpointInput) HasAllowedIps() bool {
	if o != nil && !IsNil(o.AllowedIps) {
		return true
	}

	return false
}

// SetAllowedIps gets a reference to the given []string and assigns it to the AllowedIps field.
func (o *UpdateProviderEndpointInput) SetAllowedIps(v []string) {
	o.AllowedIps = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateProviderEndpointInput) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateProviderEndpointInput) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *UpdateProviderEndpointInput) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *UpdateProviderEndpointInput) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *UpdateProviderEndpointInput) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *UpdateProviderEndpointInput) UnsetLabel() {
	o.Label.Unset()
}

// GetProviderConfig returns the ProviderConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateProviderEndpointInput) GetProviderConfig() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ProviderConfig
}

// GetProviderConfigOk returns a tuple with the ProviderConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateProviderEndpointInput) GetProviderConfigOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ProviderConfig) {
		return nil, false
	}
	return &o.ProviderConfig, true
}

// HasProviderConfig returns a boolean if a field has been set.
func (o *UpdateProviderEndpointInput) HasProviderConfig() bool {
	if o != nil && !IsNil(o.ProviderConfig) {
		return true
	}

	return false
}

// SetProviderConfig gets a reference to the given interface{} and assigns it to the ProviderConfig field.
func (o *UpdateProviderEndpointInput) SetProviderConfig(v interface{}) {
	o.ProviderConfig = v
}

// GetRotateDeliveryToken returns the RotateDeliveryToken field value if set, zero value otherwise.
func (o *UpdateProviderEndpointInput) GetRotateDeliveryToken() bool {
	if o == nil || IsNil(o.RotateDeliveryToken) {
		var ret bool
		return ret
	}
	return *o.RotateDeliveryToken
}

// GetRotateDeliveryTokenOk returns a tuple with the RotateDeliveryToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProviderEndpointInput) GetRotateDeliveryTokenOk() (*bool, bool) {
	if o == nil || IsNil(o.RotateDeliveryToken) {
		return nil, false
	}
	return o.RotateDeliveryToken, true
}

// HasRotateDeliveryToken returns a boolean if a field has been set.
func (o *UpdateProviderEndpointInput) HasRotateDeliveryToken() bool {
	if o != nil && !IsNil(o.RotateDeliveryToken) {
		return true
	}

	return false
}

// SetRotateDeliveryToken gets a reference to the given bool and assigns it to the RotateDeliveryToken field.
func (o *UpdateProviderEndpointInput) SetRotateDeliveryToken(v bool) {
	o.RotateDeliveryToken = &v
}

// GetStatus returns the Status field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateProviderEndpointInput) GetStatus() string {
	if o == nil || IsNil(o.Status.Get()) {
		var ret string
		return ret
	}
	return *o.Status.Get()
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateProviderEndpointInput) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Status.Get(), o.Status.IsSet()
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateProviderEndpointInput) HasStatus() bool {
	if o != nil && o.Status.IsSet() {
		return true
	}

	return false
}

// SetStatus gets a reference to the given NullableString and assigns it to the Status field.
func (o *UpdateProviderEndpointInput) SetStatus(v string) {
	o.Status.Set(&v)
}
// SetStatusNil sets the value for Status to be an explicit nil
func (o *UpdateProviderEndpointInput) SetStatusNil() {
	o.Status.Set(nil)
}

// UnsetStatus ensures that no value is present for Status, not even an explicit nil
func (o *UpdateProviderEndpointInput) UnsetStatus() {
	o.Status.Unset()
}

func (o UpdateProviderEndpointInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProviderEndpointInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AllowedIps != nil {
		toSerialize["allowed_ips"] = o.AllowedIps
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.ProviderConfig != nil {
		toSerialize["provider_config"] = o.ProviderConfig
	}
	if !IsNil(o.RotateDeliveryToken) {
		toSerialize["rotate_delivery_token"] = o.RotateDeliveryToken
	}
	if o.Status.IsSet() {
		toSerialize["status"] = o.Status.Get()
	}
	return toSerialize, nil
}

type NullableUpdateProviderEndpointInput struct {
	value *UpdateProviderEndpointInput
	isSet bool
}

func (v NullableUpdateProviderEndpointInput) Get() *UpdateProviderEndpointInput {
	return v.value
}

func (v *NullableUpdateProviderEndpointInput) Set(val *UpdateProviderEndpointInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProviderEndpointInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProviderEndpointInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProviderEndpointInput(val *UpdateProviderEndpointInput) *NullableUpdateProviderEndpointInput {
	return &NullableUpdateProviderEndpointInput{value: val, isSet: true}
}

func (v NullableUpdateProviderEndpointInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProviderEndpointInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
