/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestOutcomesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestOutcomesRequest{}

// IngestOutcomesRequest struct for IngestOutcomesRequest
type IngestOutcomesRequest struct {
	Outcomes []IngestOutcome `json:"outcomes"`
}

type _IngestOutcomesRequest IngestOutcomesRequest

// NewIngestOutcomesRequest instantiates a new IngestOutcomesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestOutcomesRequest(outcomes []IngestOutcome) *IngestOutcomesRequest {
	this := IngestOutcomesRequest{}
	this.Outcomes = outcomes
	return &this
}

// NewIngestOutcomesRequestWithDefaults instantiates a new IngestOutcomesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestOutcomesRequestWithDefaults() *IngestOutcomesRequest {
	this := IngestOutcomesRequest{}
	return &this
}

// GetOutcomes returns the Outcomes field value
func (o *IngestOutcomesRequest) GetOutcomes() []IngestOutcome {
	if o == nil {
		var ret []IngestOutcome
		return ret
	}

	return o.Outcomes
}

// GetOutcomesOk returns a tuple with the Outcomes field value
// and a boolean to check if the value has been set.
func (o *IngestOutcomesRequest) GetOutcomesOk() ([]IngestOutcome, bool) {
	if o == nil {
		return nil, false
	}
	return o.Outcomes, true
}

// SetOutcomes sets field value
func (o *IngestOutcomesRequest) SetOutcomes(v []IngestOutcome) {
	o.Outcomes = v
}

func (o IngestOutcomesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestOutcomesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["outcomes"] = o.Outcomes
	return toSerialize, nil
}

func (o *IngestOutcomesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"outcomes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestOutcomesRequest := _IngestOutcomesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varIngestOutcomesRequest)

	if err != nil {
		return err
	}

	*o = IngestOutcomesRequest(varIngestOutcomesRequest)

	return err
}

type NullableIngestOutcomesRequest struct {
	value *IngestOutcomesRequest
	isSet bool
}

func (v NullableIngestOutcomesRequest) Get() *IngestOutcomesRequest {
	return v.value
}

func (v *NullableIngestOutcomesRequest) Set(val *IngestOutcomesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestOutcomesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestOutcomesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestOutcomesRequest(val *IngestOutcomesRequest) *NullableIngestOutcomesRequest {
	return &NullableIngestOutcomesRequest{value: val, isSet: true}
}

func (v NullableIngestOutcomesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestOutcomesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
