/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// PipelineDeliveryStatus the model 'PipelineDeliveryStatus'
type PipelineDeliveryStatus string

// List of PipelineDeliveryStatus
const (
	PIPELINEDELIVERYSTATUS_NOT_REQUESTED PipelineDeliveryStatus = "not_requested"
	PIPELINEDELIVERYSTATUS_PENDING PipelineDeliveryStatus = "pending"
	PIPELINEDELIVERYSTATUS_DELIVERED PipelineDeliveryStatus = "delivered"
	PIPELINEDELIVERYSTATUS_RETRY_SCHEDULED PipelineDeliveryStatus = "retry_scheduled"
	PIPELINEDELIVERYSTATUS_FAILED PipelineDeliveryStatus = "failed"
)

// All allowed values of PipelineDeliveryStatus enum
var AllowedPipelineDeliveryStatusEnumValues = []PipelineDeliveryStatus{
	"not_requested",
	"pending",
	"delivered",
	"retry_scheduled",
	"failed",
}

func (v *PipelineDeliveryStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PipelineDeliveryStatus(value)
	for _, existing := range AllowedPipelineDeliveryStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid PipelineDeliveryStatus", value)
}

// NewPipelineDeliveryStatusFromValue returns a pointer to a valid PipelineDeliveryStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPipelineDeliveryStatusFromValue(v string) (*PipelineDeliveryStatus, error) {
	ev := PipelineDeliveryStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PipelineDeliveryStatus: valid values are %v", v, AllowedPipelineDeliveryStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PipelineDeliveryStatus) IsValid() bool {
	for _, existing := range AllowedPipelineDeliveryStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PipelineDeliveryStatus value
func (v PipelineDeliveryStatus) Ptr() *PipelineDeliveryStatus {
	return &v
}

type NullablePipelineDeliveryStatus struct {
	value *PipelineDeliveryStatus
	isSet bool
}

func (v NullablePipelineDeliveryStatus) Get() *PipelineDeliveryStatus {
	return v.value
}

func (v *NullablePipelineDeliveryStatus) Set(val *PipelineDeliveryStatus) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineDeliveryStatus) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineDeliveryStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineDeliveryStatus(val *PipelineDeliveryStatus) *NullablePipelineDeliveryStatus {
	return &NullablePipelineDeliveryStatus{value: val, isSet: true}
}

func (v NullablePipelineDeliveryStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineDeliveryStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

