/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// SmtpUncertaintyClass the model 'SmtpUncertaintyClass'
type SmtpUncertaintyClass string

// List of SmtpUncertaintyClass
const (
	SMTPUNCERTAINTYCLASS_TRANSIENT SmtpUncertaintyClass = "transient"
	SMTPUNCERTAINTYCLASS_POLICY_BLOCK SmtpUncertaintyClass = "policy_block"
	SMTPUNCERTAINTYCLASS_TIMEOUT SmtpUncertaintyClass = "timeout"
	SMTPUNCERTAINTYCLASS_NETWORK SmtpUncertaintyClass = "network"
	SMTPUNCERTAINTYCLASS_AMBIGUOUS_RESPONSE SmtpUncertaintyClass = "ambiguous_response"
	SMTPUNCERTAINTYCLASS_SMTP_UNREACHABLE SmtpUncertaintyClass = "smtp_unreachable"
)

// All allowed values of SmtpUncertaintyClass enum
var AllowedSmtpUncertaintyClassEnumValues = []SmtpUncertaintyClass{
	"transient",
	"policy_block",
	"timeout",
	"network",
	"ambiguous_response",
	"smtp_unreachable",
}

func (v *SmtpUncertaintyClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SmtpUncertaintyClass(value)
	for _, existing := range AllowedSmtpUncertaintyClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SmtpUncertaintyClass", value)
}

// NewSmtpUncertaintyClassFromValue returns a pointer to a valid SmtpUncertaintyClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSmtpUncertaintyClassFromValue(v string) (*SmtpUncertaintyClass, error) {
	ev := SmtpUncertaintyClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SmtpUncertaintyClass: valid values are %v", v, AllowedSmtpUncertaintyClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SmtpUncertaintyClass) IsValid() bool {
	for _, existing := range AllowedSmtpUncertaintyClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SmtpUncertaintyClass value
func (v SmtpUncertaintyClass) Ptr() *SmtpUncertaintyClass {
	return &v
}

type NullableSmtpUncertaintyClass struct {
	value *SmtpUncertaintyClass
	isSet bool
}

func (v NullableSmtpUncertaintyClass) Get() *SmtpUncertaintyClass {
	return v.value
}

func (v *NullableSmtpUncertaintyClass) Set(val *SmtpUncertaintyClass) {
	v.value = val
	v.isSet = true
}

func (v NullableSmtpUncertaintyClass) IsSet() bool {
	return v.isSet
}

func (v *NullableSmtpUncertaintyClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmtpUncertaintyClass(val *SmtpUncertaintyClass) *NullableSmtpUncertaintyClass {
	return &NullableSmtpUncertaintyClass{value: val, isSet: true}
}

func (v NullableSmtpUncertaintyClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmtpUncertaintyClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
