/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
)

// checks if the PipelineDeliveryConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PipelineDeliveryConfig{}

// PipelineDeliveryConfig struct for PipelineDeliveryConfig
type PipelineDeliveryConfig struct {
	Dashboard *bool `json:"dashboard,omitempty"`
	MaxAttempts *int32 `json:"max_attempts,omitempty"`
	RetryBackoffSeconds *int32 `json:"retry_backoff_seconds,omitempty"`
	Webhook NullablePipelineDeliveryWebhook `json:"webhook,omitempty"`
}

// NewPipelineDeliveryConfig instantiates a new PipelineDeliveryConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPipelineDeliveryConfig() *PipelineDeliveryConfig {
	this := PipelineDeliveryConfig{}
	return &this
}

// NewPipelineDeliveryConfigWithDefaults instantiates a new PipelineDeliveryConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPipelineDeliveryConfigWithDefaults() *PipelineDeliveryConfig {
	this := PipelineDeliveryConfig{}
	return &this
}

// GetDashboard returns the Dashboard field value if set, zero value otherwise.
func (o *PipelineDeliveryConfig) GetDashboard() bool {
	if o == nil || IsNil(o.Dashboard) {
		var ret bool
		return ret
	}
	return *o.Dashboard
}

// GetDashboardOk returns a tuple with the Dashboard field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineDeliveryConfig) GetDashboardOk() (*bool, bool) {
	if o == nil || IsNil(o.Dashboard) {
		return nil, false
	}
	return o.Dashboard, true
}

// HasDashboard returns a boolean if a field has been set.
func (o *PipelineDeliveryConfig) HasDashboard() bool {
	if o != nil && !IsNil(o.Dashboard) {
		return true
	}

	return false
}

// SetDashboard gets a reference to the given bool and assigns it to the Dashboard field.
func (o *PipelineDeliveryConfig) SetDashboard(v bool) {
	o.Dashboard = &v
}

// GetMaxAttempts returns the MaxAttempts field value if set, zero value otherwise.
func (o *PipelineDeliveryConfig) GetMaxAttempts() int32 {
	if o == nil || IsNil(o.MaxAttempts) {
		var ret int32
		return ret
	}
	return *o.MaxAttempts
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineDeliveryConfig) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxAttempts) {
		return nil, false
	}
	return o.MaxAttempts, true
}

// HasMaxAttempts returns a boolean if a field has been set.
func (o *PipelineDeliveryConfig) HasMaxAttempts() bool {
	if o != nil && !IsNil(o.MaxAttempts) {
		return true
	}

	return false
}

// SetMaxAttempts gets a reference to the given int32 and assigns it to the MaxAttempts field.
func (o *PipelineDeliveryConfig) SetMaxAttempts(v int32) {
	o.MaxAttempts = &v
}

// GetRetryBackoffSeconds returns the RetryBackoffSeconds field value if set, zero value otherwise.
func (o *PipelineDeliveryConfig) GetRetryBackoffSeconds() int32 {
	if o == nil || IsNil(o.RetryBackoffSeconds) {
		var ret int32
		return ret
	}
	return *o.RetryBackoffSeconds
}

// GetRetryBackoffSecondsOk returns a tuple with the RetryBackoffSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PipelineDeliveryConfig) GetRetryBackoffSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryBackoffSeconds) {
		return nil, false
	}
	return o.RetryBackoffSeconds, true
}

// HasRetryBackoffSeconds returns a boolean if a field has been set.
func (o *PipelineDeliveryConfig) HasRetryBackoffSeconds() bool {
	if o != nil && !IsNil(o.RetryBackoffSeconds) {
		return true
	}

	return false
}

// SetRetryBackoffSeconds gets a reference to the given int32 and assigns it to the RetryBackoffSeconds field.
func (o *PipelineDeliveryConfig) SetRetryBackoffSeconds(v int32) {
	o.RetryBackoffSeconds = &v
}

// GetWebhook returns the Webhook field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PipelineDeliveryConfig) GetWebhook() PipelineDeliveryWebhook {
	if o == nil || IsNil(o.Webhook.Get()) {
		var ret PipelineDeliveryWebhook
		return ret
	}
	return *o.Webhook.Get()
}

// GetWebhookOk returns a tuple with the Webhook field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PipelineDeliveryConfig) GetWebhookOk() (*PipelineDeliveryWebhook, bool) {
	if o == nil {
		return nil, false
	}
	return o.Webhook.Get(), o.Webhook.IsSet()
}

// HasWebhook returns a boolean if a field has been set.
func (o *PipelineDeliveryConfig) HasWebhook() bool {
	if o != nil && o.Webhook.IsSet() {
		return true
	}

	return false
}

// SetWebhook gets a reference to the given NullablePipelineDeliveryWebhook and assigns it to the Webhook field.
func (o *PipelineDeliveryConfig) SetWebhook(v PipelineDeliveryWebhook) {
	o.Webhook.Set(&v)
}
// SetWebhookNil sets the value for Webhook to be an explicit nil
func (o *PipelineDeliveryConfig) SetWebhookNil() {
	o.Webhook.Set(nil)
}

// UnsetWebhook ensures that no value is present for Webhook, not even an explicit nil
func (o *PipelineDeliveryConfig) UnsetWebhook() {
	o.Webhook.Unset()
}

func (o PipelineDeliveryConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PipelineDeliveryConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dashboard) {
		toSerialize["dashboard"] = o.Dashboard
	}
	if !IsNil(o.MaxAttempts) {
		toSerialize["max_attempts"] = o.MaxAttempts
	}
	if !IsNil(o.RetryBackoffSeconds) {
		toSerialize["retry_backoff_seconds"] = o.RetryBackoffSeconds
	}
	if o.Webhook.IsSet() {
		toSerialize["webhook"] = o.Webhook.Get()
	}
	return toSerialize, nil
}

type NullablePipelineDeliveryConfig struct {
	value *PipelineDeliveryConfig
	isSet bool
}

func (v NullablePipelineDeliveryConfig) Get() *PipelineDeliveryConfig {
	return v.value
}

func (v *NullablePipelineDeliveryConfig) Set(val *PipelineDeliveryConfig) {
	v.value = val
	v.isSet = true
}

func (v NullablePipelineDeliveryConfig) IsSet() bool {
	return v.isSet
}

func (v *NullablePipelineDeliveryConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePipelineDeliveryConfig(val *PipelineDeliveryConfig) *NullablePipelineDeliveryConfig {
	return &NullablePipelineDeliveryConfig{value: val, isSet: true}
}

func (v NullablePipelineDeliveryConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePipelineDeliveryConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


