/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IngestRowError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IngestRowError{}

// IngestRowError struct for IngestRowError
type IngestRowError struct {
	Email string `json:"email"`
	Index int32 `json:"index"`
	Message string `json:"message"`
}

type _IngestRowError IngestRowError

// NewIngestRowError instantiates a new IngestRowError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestRowError(email string, index int32, message string) *IngestRowError {
	this := IngestRowError{}
	this.Email = email
	this.Index = index
	this.Message = message
	return &this
}

// NewIngestRowErrorWithDefaults instantiates a new IngestRowError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestRowErrorWithDefaults() *IngestRowError {
	this := IngestRowError{}
	return &this
}

// GetEmail returns the Email field value
func (o *IngestRowError) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *IngestRowError) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *IngestRowError) SetEmail(v string) {
	o.Email = v
}

// GetIndex returns the Index field value
func (o *IngestRowError) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *IngestRowError) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *IngestRowError) SetIndex(v int32) {
	o.Index = v
}

// GetMessage returns the Message field value
func (o *IngestRowError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *IngestRowError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *IngestRowError) SetMessage(v string) {
	o.Message = v
}

func (o IngestRowError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IngestRowError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["index"] = o.Index
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *IngestRowError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"index",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIngestRowError := _IngestRowError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varIngestRowError)

	if err != nil {
		return err
	}

	*o = IngestRowError(varIngestRowError)

	return err
}

type NullableIngestRowError struct {
	value *IngestRowError
	isSet bool
}

func (v NullableIngestRowError) Get() *IngestRowError {
	return v.value
}

func (v *NullableIngestRowError) Set(val *IngestRowError) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestRowError) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestRowError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestRowError(val *IngestRowError) *NullableIngestRowError {
	return &NullableIngestRowError{value: val, isSet: true}
}

func (v NullableIngestRowError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestRowError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
