/*
Reacher

### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// SubReason the model 'SubReason'
type SubReason string

// List of SubReason
const (
	SUBREASON_DELIVERABLE SubReason = "deliverable"
	SUBREASON_INVALID_SYNTAX SubReason = "invalid_syntax"
	SUBREASON_INVALID_RECIPIENT SubReason = "invalid_recipient"
	SUBREASON_PROVIDER_REJECTED SubReason = "provider_rejected"
	SUBREASON_SMTP_UNDELIVERABLE SubReason = "smtp_undeliverable"
	SUBREASON_DISABLED_MAILBOX SubReason = "disabled_mailbox"
	SUBREASON_NO_MX SubReason = "no_mx"
	SUBREASON_SMTP_ERROR SubReason = "smtp_error"
	SUBREASON_SMTP_UNREACHABLE SubReason = "smtp_unreachable"
	SUBREASON_CATCH_ALL SubReason = "catch_all"
	SUBREASON_FULL_INBOX SubReason = "full_inbox"
	SUBREASON_DISPOSABLE SubReason = "disposable"
	SUBREASON_ROLE_ACCOUNT SubReason = "role_account"
	SUBREASON_SPAM_TRAP SubReason = "spam_trap"
	SUBREASON_RISKY SubReason = "risky"
	SUBREASON_UNKNOWN SubReason = "unknown"
)

// All allowed values of SubReason enum
var AllowedSubReasonEnumValues = []SubReason{
	"deliverable",
	"invalid_syntax",
	"invalid_recipient",
	"provider_rejected",
	"smtp_undeliverable",
	"disabled_mailbox",
	"no_mx",
	"smtp_error",
	"smtp_unreachable",
	"catch_all",
	"full_inbox",
	"disposable",
	"role_account",
	"spam_trap",
	"risky",
	"unknown",
}

func (v *SubReason) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SubReason(value)
	for _, existing := range AllowedSubReasonEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SubReason", value)
}

// NewSubReasonFromValue returns a pointer to a valid SubReason
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSubReasonFromValue(v string) (*SubReason, error) {
	ev := SubReason(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SubReason: valid values are %v", v, AllowedSubReasonEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SubReason) IsValid() bool {
	for _, existing := range AllowedSubReasonEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SubReason value
func (v SubReason) Ptr() *SubReason {
	return &v
}

type NullableSubReason struct {
	value *SubReason
	isSet bool
}

func (v NullableSubReason) Get() *SubReason {
	return v.value
}

func (v *NullableSubReason) Set(val *SubReason) {
	v.value = val
	v.isSet = true
}

func (v NullableSubReason) IsSet() bool {
	return v.isSet
}

func (v *NullableSubReason) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubReason(val *SubReason) *NullableSubReason {
	return &NullableSubReason{value: val, isSet: true}
}

func (v NullableSubReason) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubReason) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

