/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"fmt"
)

// GmailVerifMethod Enumeration describing the method used to verify Gmail emails.
type GmailVerifMethod string

// List of GmailVerifMethod
const (
	GMAILVERIFMETHOD_SMTP GmailVerifMethod = "Smtp"
)

// All allowed values of GmailVerifMethod enum
var AllowedGmailVerifMethodEnumValues = []GmailVerifMethod{
	"Smtp",
}

func (v *GmailVerifMethod) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := GmailVerifMethod(value)
	for _, existing := range AllowedGmailVerifMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid GmailVerifMethod", value)
}

// NewGmailVerifMethodFromValue returns a pointer to a valid GmailVerifMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewGmailVerifMethodFromValue(v string) (*GmailVerifMethod, error) {
	ev := GmailVerifMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for GmailVerifMethod: valid values are %v", v, AllowedGmailVerifMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v GmailVerifMethod) IsValid() bool {
	for _, existing := range AllowedGmailVerifMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to GmailVerifMethod value
func (v GmailVerifMethod) Ptr() *GmailVerifMethod {
	return &v
}

type NullableGmailVerifMethod struct {
	value *GmailVerifMethod
	isSet bool
}

func (v NullableGmailVerifMethod) Get() *GmailVerifMethod {
	return v.value
}

func (v *NullableGmailVerifMethod) Set(val *GmailVerifMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableGmailVerifMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableGmailVerifMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGmailVerifMethod(val *GmailVerifMethod) *NullableGmailVerifMethod {
	return &NullableGmailVerifMethod{value: val, isSet: true}
}

func (v NullableGmailVerifMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGmailVerifMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

