/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiffRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiffRow{}

// DiffRow struct for DiffRow
type DiffRow struct {
	BaseCategory NullableString `json:"base_category,omitempty"`
	BaseRowIndex NullableInt32 `json:"base_row_index,omitempty"`
	BaseScore NullableInt32 `json:"base_score,omitempty"`
	BaseTaskId NullableInt32 `json:"base_task_id,omitempty"`
	CanonicalEmail string `json:"canonical_email"`
	ChangeType string `json:"change_type"`
	CompareCategory NullableString `json:"compare_category,omitempty"`
	CompareRowIndex NullableInt32 `json:"compare_row_index,omitempty"`
	CompareScore NullableInt32 `json:"compare_score,omitempty"`
	CompareTaskId NullableInt32 `json:"compare_task_id,omitempty"`
}

type _DiffRow DiffRow

// NewDiffRow instantiates a new DiffRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiffRow(canonicalEmail string, changeType string) *DiffRow {
	this := DiffRow{}
	this.CanonicalEmail = canonicalEmail
	this.ChangeType = changeType
	return &this
}

// NewDiffRowWithDefaults instantiates a new DiffRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiffRowWithDefaults() *DiffRow {
	this := DiffRow{}
	return &this
}

// GetBaseCategory returns the BaseCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetBaseCategory() string {
	if o == nil || IsNil(o.BaseCategory.Get()) {
		var ret string
		return ret
	}
	return *o.BaseCategory.Get()
}

// GetBaseCategoryOk returns a tuple with the BaseCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetBaseCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseCategory.Get(), o.BaseCategory.IsSet()
}

// HasBaseCategory returns a boolean if a field has been set.
func (o *DiffRow) HasBaseCategory() bool {
	if o != nil && o.BaseCategory.IsSet() {
		return true
	}

	return false
}

// SetBaseCategory gets a reference to the given NullableString and assigns it to the BaseCategory field.
func (o *DiffRow) SetBaseCategory(v string) {
	o.BaseCategory.Set(&v)
}
// SetBaseCategoryNil sets the value for BaseCategory to be an explicit nil
func (o *DiffRow) SetBaseCategoryNil() {
	o.BaseCategory.Set(nil)
}

// UnsetBaseCategory ensures that no value is present for BaseCategory, not even an explicit nil
func (o *DiffRow) UnsetBaseCategory() {
	o.BaseCategory.Unset()
}

// GetBaseRowIndex returns the BaseRowIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetBaseRowIndex() int32 {
	if o == nil || IsNil(o.BaseRowIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseRowIndex.Get()
}

// GetBaseRowIndexOk returns a tuple with the BaseRowIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetBaseRowIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseRowIndex.Get(), o.BaseRowIndex.IsSet()
}

// HasBaseRowIndex returns a boolean if a field has been set.
func (o *DiffRow) HasBaseRowIndex() bool {
	if o != nil && o.BaseRowIndex.IsSet() {
		return true
	}

	return false
}

// SetBaseRowIndex gets a reference to the given NullableInt32 and assigns it to the BaseRowIndex field.
func (o *DiffRow) SetBaseRowIndex(v int32) {
	o.BaseRowIndex.Set(&v)
}
// SetBaseRowIndexNil sets the value for BaseRowIndex to be an explicit nil
func (o *DiffRow) SetBaseRowIndexNil() {
	o.BaseRowIndex.Set(nil)
}

// UnsetBaseRowIndex ensures that no value is present for BaseRowIndex, not even an explicit nil
func (o *DiffRow) UnsetBaseRowIndex() {
	o.BaseRowIndex.Unset()
}

// GetBaseScore returns the BaseScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetBaseScore() int32 {
	if o == nil || IsNil(o.BaseScore.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseScore.Get()
}

// GetBaseScoreOk returns a tuple with the BaseScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetBaseScoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseScore.Get(), o.BaseScore.IsSet()
}

// HasBaseScore returns a boolean if a field has been set.
func (o *DiffRow) HasBaseScore() bool {
	if o != nil && o.BaseScore.IsSet() {
		return true
	}

	return false
}

// SetBaseScore gets a reference to the given NullableInt32 and assigns it to the BaseScore field.
func (o *DiffRow) SetBaseScore(v int32) {
	o.BaseScore.Set(&v)
}
// SetBaseScoreNil sets the value for BaseScore to be an explicit nil
func (o *DiffRow) SetBaseScoreNil() {
	o.BaseScore.Set(nil)
}

// UnsetBaseScore ensures that no value is present for BaseScore, not even an explicit nil
func (o *DiffRow) UnsetBaseScore() {
	o.BaseScore.Unset()
}

// GetBaseTaskId returns the BaseTaskId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetBaseTaskId() int32 {
	if o == nil || IsNil(o.BaseTaskId.Get()) {
		var ret int32
		return ret
	}
	return *o.BaseTaskId.Get()
}

// GetBaseTaskIdOk returns a tuple with the BaseTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetBaseTaskIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseTaskId.Get(), o.BaseTaskId.IsSet()
}

// HasBaseTaskId returns a boolean if a field has been set.
func (o *DiffRow) HasBaseTaskId() bool {
	if o != nil && o.BaseTaskId.IsSet() {
		return true
	}

	return false
}

// SetBaseTaskId gets a reference to the given NullableInt32 and assigns it to the BaseTaskId field.
func (o *DiffRow) SetBaseTaskId(v int32) {
	o.BaseTaskId.Set(&v)
}
// SetBaseTaskIdNil sets the value for BaseTaskId to be an explicit nil
func (o *DiffRow) SetBaseTaskIdNil() {
	o.BaseTaskId.Set(nil)
}

// UnsetBaseTaskId ensures that no value is present for BaseTaskId, not even an explicit nil
func (o *DiffRow) UnsetBaseTaskId() {
	o.BaseTaskId.Unset()
}

// GetCanonicalEmail returns the CanonicalEmail field value
func (o *DiffRow) GetCanonicalEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CanonicalEmail
}

// GetCanonicalEmailOk returns a tuple with the CanonicalEmail field value
// and a boolean to check if the value has been set.
func (o *DiffRow) GetCanonicalEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CanonicalEmail, true
}

// SetCanonicalEmail sets field value
func (o *DiffRow) SetCanonicalEmail(v string) {
	o.CanonicalEmail = v
}

// GetChangeType returns the ChangeType field value
func (o *DiffRow) GetChangeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeType
}

// GetChangeTypeOk returns a tuple with the ChangeType field value
// and a boolean to check if the value has been set.
func (o *DiffRow) GetChangeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeType, true
}

// SetChangeType sets field value
func (o *DiffRow) SetChangeType(v string) {
	o.ChangeType = v
}

// GetCompareCategory returns the CompareCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetCompareCategory() string {
	if o == nil || IsNil(o.CompareCategory.Get()) {
		var ret string
		return ret
	}
	return *o.CompareCategory.Get()
}

// GetCompareCategoryOk returns a tuple with the CompareCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetCompareCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareCategory.Get(), o.CompareCategory.IsSet()
}

// HasCompareCategory returns a boolean if a field has been set.
func (o *DiffRow) HasCompareCategory() bool {
	if o != nil && o.CompareCategory.IsSet() {
		return true
	}

	return false
}

// SetCompareCategory gets a reference to the given NullableString and assigns it to the CompareCategory field.
func (o *DiffRow) SetCompareCategory(v string) {
	o.CompareCategory.Set(&v)
}
// SetCompareCategoryNil sets the value for CompareCategory to be an explicit nil
func (o *DiffRow) SetCompareCategoryNil() {
	o.CompareCategory.Set(nil)
}

// UnsetCompareCategory ensures that no value is present for CompareCategory, not even an explicit nil
func (o *DiffRow) UnsetCompareCategory() {
	o.CompareCategory.Unset()
}

// GetCompareRowIndex returns the CompareRowIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetCompareRowIndex() int32 {
	if o == nil || IsNil(o.CompareRowIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.CompareRowIndex.Get()
}

// GetCompareRowIndexOk returns a tuple with the CompareRowIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetCompareRowIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareRowIndex.Get(), o.CompareRowIndex.IsSet()
}

// HasCompareRowIndex returns a boolean if a field has been set.
func (o *DiffRow) HasCompareRowIndex() bool {
	if o != nil && o.CompareRowIndex.IsSet() {
		return true
	}

	return false
}

// SetCompareRowIndex gets a reference to the given NullableInt32 and assigns it to the CompareRowIndex field.
func (o *DiffRow) SetCompareRowIndex(v int32) {
	o.CompareRowIndex.Set(&v)
}
// SetCompareRowIndexNil sets the value for CompareRowIndex to be an explicit nil
func (o *DiffRow) SetCompareRowIndexNil() {
	o.CompareRowIndex.Set(nil)
}

// UnsetCompareRowIndex ensures that no value is present for CompareRowIndex, not even an explicit nil
func (o *DiffRow) UnsetCompareRowIndex() {
	o.CompareRowIndex.Unset()
}

// GetCompareScore returns the CompareScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetCompareScore() int32 {
	if o == nil || IsNil(o.CompareScore.Get()) {
		var ret int32
		return ret
	}
	return *o.CompareScore.Get()
}

// GetCompareScoreOk returns a tuple with the CompareScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetCompareScoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareScore.Get(), o.CompareScore.IsSet()
}

// HasCompareScore returns a boolean if a field has been set.
func (o *DiffRow) HasCompareScore() bool {
	if o != nil && o.CompareScore.IsSet() {
		return true
	}

	return false
}

// SetCompareScore gets a reference to the given NullableInt32 and assigns it to the CompareScore field.
func (o *DiffRow) SetCompareScore(v int32) {
	o.CompareScore.Set(&v)
}
// SetCompareScoreNil sets the value for CompareScore to be an explicit nil
func (o *DiffRow) SetCompareScoreNil() {
	o.CompareScore.Set(nil)
}

// UnsetCompareScore ensures that no value is present for CompareScore, not even an explicit nil
func (o *DiffRow) UnsetCompareScore() {
	o.CompareScore.Unset()
}

// GetCompareTaskId returns the CompareTaskId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DiffRow) GetCompareTaskId() int32 {
	if o == nil || IsNil(o.CompareTaskId.Get()) {
		var ret int32
		return ret
	}
	return *o.CompareTaskId.Get()
}

// GetCompareTaskIdOk returns a tuple with the CompareTaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DiffRow) GetCompareTaskIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareTaskId.Get(), o.CompareTaskId.IsSet()
}

// HasCompareTaskId returns a boolean if a field has been set.
func (o *DiffRow) HasCompareTaskId() bool {
	if o != nil && o.CompareTaskId.IsSet() {
		return true
	}

	return false
}

// SetCompareTaskId gets a reference to the given NullableInt32 and assigns it to the CompareTaskId field.
func (o *DiffRow) SetCompareTaskId(v int32) {
	o.CompareTaskId.Set(&v)
}
// SetCompareTaskIdNil sets the value for CompareTaskId to be an explicit nil
func (o *DiffRow) SetCompareTaskIdNil() {
	o.CompareTaskId.Set(nil)
}

// UnsetCompareTaskId ensures that no value is present for CompareTaskId, not even an explicit nil
func (o *DiffRow) UnsetCompareTaskId() {
	o.CompareTaskId.Unset()
}

func (o DiffRow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiffRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.BaseCategory.IsSet() {
		toSerialize["base_category"] = o.BaseCategory.Get()
	}
	if o.BaseRowIndex.IsSet() {
		toSerialize["base_row_index"] = o.BaseRowIndex.Get()
	}
	if o.BaseScore.IsSet() {
		toSerialize["base_score"] = o.BaseScore.Get()
	}
	if o.BaseTaskId.IsSet() {
		toSerialize["base_task_id"] = o.BaseTaskId.Get()
	}
	toSerialize["canonical_email"] = o.CanonicalEmail
	toSerialize["change_type"] = o.ChangeType
	if o.CompareCategory.IsSet() {
		toSerialize["compare_category"] = o.CompareCategory.Get()
	}
	if o.CompareRowIndex.IsSet() {
		toSerialize["compare_row_index"] = o.CompareRowIndex.Get()
	}
	if o.CompareScore.IsSet() {
		toSerialize["compare_score"] = o.CompareScore.Get()
	}
	if o.CompareTaskId.IsSet() {
		toSerialize["compare_task_id"] = o.CompareTaskId.Get()
	}
	return toSerialize, nil
}

func (o *DiffRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"canonical_email",
		"change_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiffRow := _DiffRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varDiffRow)

	if err != nil {
		return err
	}

	*o = DiffRow(varDiffRow)

	return err
}

type NullableDiffRow struct {
	value *DiffRow
	isSet bool
}

func (v NullableDiffRow) Get() *DiffRow {
	return v.value
}

func (v *NullableDiffRow) Set(val *DiffRow) {
	v.value = val
	v.isSet = true
}

func (v NullableDiffRow) IsSet() bool {
	return v.isSet
}

func (v *NullableDiffRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiffRow(val *DiffRow) *NullableDiffRow {
	return &NullableDiffRow{value: val, isSet: true}
}

func (v NullableDiffRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiffRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
