/*
Reacher

### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.

API version: 0.11.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateAlertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAlertRequest{}

// UpdateAlertRequest struct for UpdateAlertRequest
type UpdateAlertRequest struct {
	Status string `json:"status"`
}

type _UpdateAlertRequest UpdateAlertRequest

// NewUpdateAlertRequest instantiates a new UpdateAlertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAlertRequest(status string) *UpdateAlertRequest {
	this := UpdateAlertRequest{}
	this.Status = status
	return &this
}

// NewUpdateAlertRequestWithDefaults instantiates a new UpdateAlertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAlertRequestWithDefaults() *UpdateAlertRequest {
	this := UpdateAlertRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdateAlertRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdateAlertRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdateAlertRequest) SetStatus(v string) {
	o.Status = v
}

func (o UpdateAlertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAlertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdateAlertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAlertRequest := _UpdateAlertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varUpdateAlertRequest)

	if err != nil {
		return err
	}

	*o = UpdateAlertRequest(varUpdateAlertRequest)

	return err
}

type NullableUpdateAlertRequest struct {
	value *UpdateAlertRequest
	isSet bool
}

func (v NullableUpdateAlertRequest) Get() *UpdateAlertRequest {
	return v.value
}

func (v *NullableUpdateAlertRequest) Set(val *UpdateAlertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAlertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAlertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAlertRequest(val *UpdateAlertRequest) *NullableUpdateAlertRequest {
	return &NullableUpdateAlertRequest{value: val, isSet: true}
}

func (v NullableUpdateAlertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAlertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
