/*
Reacher

### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.

API version: 4.3.0
Contact: amaury@reacher.email
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package reacher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminUpdateQuotaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminUpdateQuotaRequest{}

// AdminUpdateQuotaRequest struct for AdminUpdateQuotaRequest
type AdminUpdateQuotaRequest struct {
	MonthlyEmailLimit NullableInt32 `json:"monthly_email_limit"`
}

type _AdminUpdateQuotaRequest AdminUpdateQuotaRequest

// NewAdminUpdateQuotaRequest instantiates a new AdminUpdateQuotaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminUpdateQuotaRequest(monthlyEmailLimit NullableInt32) *AdminUpdateQuotaRequest {
	this := AdminUpdateQuotaRequest{}
	this.MonthlyEmailLimit = monthlyEmailLimit
	return &this
}

// NewAdminUpdateQuotaRequestWithDefaults instantiates a new AdminUpdateQuotaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminUpdateQuotaRequestWithDefaults() *AdminUpdateQuotaRequest {
	this := AdminUpdateQuotaRequest{}
	return &this
}

// GetMonthlyEmailLimit returns the MonthlyEmailLimit field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *AdminUpdateQuotaRequest) GetMonthlyEmailLimit() int32 {
	if o == nil || o.MonthlyEmailLimit.Get() == nil {
		var ret int32
		return ret
	}

	return *o.MonthlyEmailLimit.Get()
}

// GetMonthlyEmailLimitOk returns a tuple with the MonthlyEmailLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AdminUpdateQuotaRequest) GetMonthlyEmailLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MonthlyEmailLimit.Get(), o.MonthlyEmailLimit.IsSet()
}

// SetMonthlyEmailLimit sets field value
func (o *AdminUpdateQuotaRequest) SetMonthlyEmailLimit(v int32) {
	o.MonthlyEmailLimit.Set(&v)
}

func (o AdminUpdateQuotaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminUpdateQuotaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["monthly_email_limit"] = o.MonthlyEmailLimit.Get()
	return toSerialize, nil
}

func (o *AdminUpdateQuotaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"monthly_email_limit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminUpdateQuotaRequest := _AdminUpdateQuotaRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	err = decoder.Decode(&varAdminUpdateQuotaRequest)

	if err != nil {
		return err
	}

	*o = AdminUpdateQuotaRequest(varAdminUpdateQuotaRequest)

	return err
}

type NullableAdminUpdateQuotaRequest struct {
	value *AdminUpdateQuotaRequest
	isSet bool
}

func (v NullableAdminUpdateQuotaRequest) Get() *AdminUpdateQuotaRequest {
	return v.value
}

func (v *NullableAdminUpdateQuotaRequest) Set(val *AdminUpdateQuotaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminUpdateQuotaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminUpdateQuotaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminUpdateQuotaRequest(val *AdminUpdateQuotaRequest) *NullableAdminUpdateQuotaRequest {
	return &NullableAdminUpdateQuotaRequest{value: val, isSet: true}
}

func (v NullableAdminUpdateQuotaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminUpdateQuotaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
