/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * AccountApi - axios parameter creator
 * @export
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new API key for the authenticated tenant.
         * @summary POST /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantApiKey: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/api-keys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return a single API key for the authenticated tenant.
         * @summary GET /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantApiKey: async (keyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'keyId' is not null or undefined
            assertParamExists('getTenantApiKey', 'keyId', keyId)
            const localVarPath = `/v1/me/api-keys/{key_id}`
                .replace(`{${"key_id"}}`, encodeURIComponent(String(keyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List API keys for the authenticated tenant.
         * @summary GET /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTenantApiKeys: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/api-keys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Revoke an API key.
         * @summary DELETE /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeTenantApiKey: async (keyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'keyId' is not null or undefined
            assertParamExists('revokeTenantApiKey', 'keyId', keyId)
            const localVarPath = `/v1/me/api-keys/{key_id}`
                .replace(`{${"key_id"}}`, encodeURIComponent(String(keyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update metadata for an existing API key.
         * @summary PATCH /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantApiKey: async (keyId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'keyId' is not null or undefined
            assertParamExists('updateTenantApiKey', 'keyId', keyId)
            const localVarPath = `/v1/me/api-keys/{key_id}`
                .replace(`{${"key_id"}}`, encodeURIComponent(String(keyId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the authenticated tenant context and quota metadata.
         * @summary GET /v1/me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1Me: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountApi - functional programming interface
 * @export
 */
export const AccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a new API key for the authenticated tenant.
         * @summary POST /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTenantApiKey(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTenantApiKey(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.createTenantApiKey']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return a single API key for the authenticated tenant.
         * @summary GET /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTenantApiKey(keyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTenantApiKey(keyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.getTenantApiKey']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List API keys for the authenticated tenant.
         * @summary GET /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTenantApiKeys(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTenantApiKeys(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.listTenantApiKeys']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Revoke an API key.
         * @summary DELETE /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async revokeTenantApiKey(keyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.revokeTenantApiKey(keyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.revokeTenantApiKey']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update metadata for an existing API key.
         * @summary PATCH /v1/me/api-keys/{key_id}
         * @param {string} keyId API key identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateTenantApiKey(keyId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTenantApiKey(keyId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.updateTenantApiKey']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the authenticated tenant context and quota metadata.
         * @summary GET /v1/me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1Me(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1Me(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.v1Me']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountApi - factory interface
 * @export
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountApiFp(configuration)
    return {
        /**
         * Create a new API key for the authenticated tenant.
         * @summary POST /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTenantApiKey(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.createTenantApiKey(options).then((request) => request(axios, basePath));
        },
        /**
         * Return a single API key for the authenticated tenant.
         * @summary GET /v1/me/api-keys/{key_id}
         * @param {AccountApiGetTenantApiKeyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTenantApiKey(requestParameters: AccountApiGetTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getTenantApiKey(requestParameters.keyId, options).then((request) => request(axios, basePath));
        },
        /**
         * List API keys for the authenticated tenant.
         * @summary GET /v1/me/api-keys
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTenantApiKeys(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.listTenantApiKeys(options).then((request) => request(axios, basePath));
        },
        /**
         * Revoke an API key.
         * @summary DELETE /v1/me/api-keys/{key_id}
         * @param {AccountApiRevokeTenantApiKeyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        revokeTenantApiKey(requestParameters: AccountApiRevokeTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.revokeTenantApiKey(requestParameters.keyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Update metadata for an existing API key.
         * @summary PATCH /v1/me/api-keys/{key_id}
         * @param {AccountApiUpdateTenantApiKeyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateTenantApiKey(requestParameters: AccountApiUpdateTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.updateTenantApiKey(requestParameters.keyId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the authenticated tenant context and quota metadata.
         * @summary GET /v1/me
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1Me(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1Me(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountApi - interface
 * @export
 * @interface AccountApi
 */
export interface AccountApiInterface {
    /**
     * Create a new API key for the authenticated tenant.
     * @summary POST /v1/me/api-keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    createTenantApiKey(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Return a single API key for the authenticated tenant.
     * @summary GET /v1/me/api-keys/{key_id}
     * @param {AccountApiGetTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    getTenantApiKey(requestParameters: AccountApiGetTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * List API keys for the authenticated tenant.
     * @summary GET /v1/me/api-keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    listTenantApiKeys(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Revoke an API key.
     * @summary DELETE /v1/me/api-keys/{key_id}
     * @param {AccountApiRevokeTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    revokeTenantApiKey(requestParameters: AccountApiRevokeTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Update metadata for an existing API key.
     * @summary PATCH /v1/me/api-keys/{key_id}
     * @param {AccountApiUpdateTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    updateTenantApiKey(requestParameters: AccountApiUpdateTenantApiKeyRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Returns the authenticated tenant context and quota metadata.
     * @summary GET /v1/me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApiInterface
     */
    v1Me(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for getTenantApiKey operation in AccountApi.
 * @export
 * @interface AccountApiGetTenantApiKeyRequest
 */
export interface AccountApiGetTenantApiKeyRequest {
    /**
     * API key identifier
     * @type {string}
     * @memberof AccountApiGetTenantApiKey
     */
    readonly keyId: string
}

/**
 * Request parameters for revokeTenantApiKey operation in AccountApi.
 * @export
 * @interface AccountApiRevokeTenantApiKeyRequest
 */
export interface AccountApiRevokeTenantApiKeyRequest {
    /**
     * API key identifier
     * @type {string}
     * @memberof AccountApiRevokeTenantApiKey
     */
    readonly keyId: string
}

/**
 * Request parameters for updateTenantApiKey operation in AccountApi.
 * @export
 * @interface AccountApiUpdateTenantApiKeyRequest
 */
export interface AccountApiUpdateTenantApiKeyRequest {
    /**
     * API key identifier
     * @type {string}
     * @memberof AccountApiUpdateTenantApiKey
     */
    readonly keyId: string
}

/**
 * AccountApi - object-oriented interface
 * @export
 * @class AccountApi
 * @extends {BaseAPI}
 */
export class AccountApi extends BaseAPI implements AccountApiInterface {
    /**
     * Create a new API key for the authenticated tenant.
     * @summary POST /v1/me/api-keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public createTenantApiKey(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).createTenantApiKey(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return a single API key for the authenticated tenant.
     * @summary GET /v1/me/api-keys/{key_id}
     * @param {AccountApiGetTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public getTenantApiKey(requestParameters: AccountApiGetTenantApiKeyRequest, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).getTenantApiKey(requestParameters.keyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List API keys for the authenticated tenant.
     * @summary GET /v1/me/api-keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public listTenantApiKeys(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).listTenantApiKeys(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Revoke an API key.
     * @summary DELETE /v1/me/api-keys/{key_id}
     * @param {AccountApiRevokeTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public revokeTenantApiKey(requestParameters: AccountApiRevokeTenantApiKeyRequest, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).revokeTenantApiKey(requestParameters.keyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update metadata for an existing API key.
     * @summary PATCH /v1/me/api-keys/{key_id}
     * @param {AccountApiUpdateTenantApiKeyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public updateTenantApiKey(requestParameters: AccountApiUpdateTenantApiKeyRequest, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).updateTenantApiKey(requestParameters.keyId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the authenticated tenant context and quota metadata.
     * @summary GET /v1/me
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AccountApi
     */
    public v1Me(options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).v1Me(options).then((request) => request(this.axios, this.basePath));
    }
}

