/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * AdminJobsApi - axios parameter creator
 * @export
 */
export const AdminJobsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetch a single job.
         * @summary GET /v1/admin/jobs/{job_id}
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJob: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getJob', 'jobId', jobId)
            const localVarPath = `/v1/admin/jobs/{job_id}`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch events for a job.
         * @summary GET /v1/admin/jobs/{job_id}/events
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobEvents: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getJobEvents', 'jobId', jobId)
            const localVarPath = `/v1/admin/jobs/{job_id}/events`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch task results for a job.
         * @summary GET /v1/admin/jobs/{job_id}/results
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobResults: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getJobResults', 'jobId', jobId)
            const localVarPath = `/v1/admin/jobs/{job_id}/results`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List jobs across all tenants with optional filters.
         * @summary GET /v1/admin/jobs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobs: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/admin/jobs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List jobs scoped to one tenant.
         * @summary GET /v1/admin/tenants/{tenant_id}/jobs
         * @param {string} tenantId Tenant identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTenantJobs: async (tenantId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('listTenantJobs', 'tenantId', tenantId)
            const localVarPath = `/v1/admin/tenants/{tenant_id}/jobs`
                .replace(`{${"tenant_id"}}`, encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminJobsApi - functional programming interface
 * @export
 */
export const AdminJobsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AdminJobsApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetch a single job.
         * @summary GET /v1/admin/jobs/{job_id}
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJob(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJob(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminJobsApi.getJob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch events for a job.
         * @summary GET /v1/admin/jobs/{job_id}/events
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobEvents(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobEvents(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminJobsApi.getJobEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Fetch task results for a job.
         * @summary GET /v1/admin/jobs/{job_id}/results
         * @param {number} jobId Job identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobResults(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobResults(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminJobsApi.getJobResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List jobs across all tenants with optional filters.
         * @summary GET /v1/admin/jobs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listJobs(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listJobs(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminJobsApi.listJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List jobs scoped to one tenant.
         * @summary GET /v1/admin/tenants/{tenant_id}/jobs
         * @param {string} tenantId Tenant identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTenantJobs(tenantId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTenantJobs(tenantId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AdminJobsApi.listTenantJobs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AdminJobsApi - factory interface
 * @export
 */
export const AdminJobsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AdminJobsApiFp(configuration)
    return {
        /**
         * Fetch a single job.
         * @summary GET /v1/admin/jobs/{job_id}
         * @param {AdminJobsApiGetJobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJob(requestParameters: AdminJobsApiGetJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getJob(requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch events for a job.
         * @summary GET /v1/admin/jobs/{job_id}/events
         * @param {AdminJobsApiGetJobEventsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobEvents(requestParameters: AdminJobsApiGetJobEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getJobEvents(requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch task results for a job.
         * @summary GET /v1/admin/jobs/{job_id}/results
         * @param {AdminJobsApiGetJobResultsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobResults(requestParameters: AdminJobsApiGetJobResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getJobResults(requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * List jobs across all tenants with optional filters.
         * @summary GET /v1/admin/jobs
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listJobs(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.listJobs(options).then((request) => request(axios, basePath));
        },
        /**
         * List jobs scoped to one tenant.
         * @summary GET /v1/admin/tenants/{tenant_id}/jobs
         * @param {AdminJobsApiListTenantJobsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTenantJobs(requestParameters: AdminJobsApiListTenantJobsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.listTenantJobs(requestParameters.tenantId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminJobsApi - interface
 * @export
 * @interface AdminJobsApi
 */
export interface AdminJobsApiInterface {
    /**
     * Fetch a single job.
     * @summary GET /v1/admin/jobs/{job_id}
     * @param {AdminJobsApiGetJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApiInterface
     */
    getJob(requestParameters: AdminJobsApiGetJobRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Fetch events for a job.
     * @summary GET /v1/admin/jobs/{job_id}/events
     * @param {AdminJobsApiGetJobEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApiInterface
     */
    getJobEvents(requestParameters: AdminJobsApiGetJobEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Fetch task results for a job.
     * @summary GET /v1/admin/jobs/{job_id}/results
     * @param {AdminJobsApiGetJobResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApiInterface
     */
    getJobResults(requestParameters: AdminJobsApiGetJobResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * List jobs across all tenants with optional filters.
     * @summary GET /v1/admin/jobs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApiInterface
     */
    listJobs(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * List jobs scoped to one tenant.
     * @summary GET /v1/admin/tenants/{tenant_id}/jobs
     * @param {AdminJobsApiListTenantJobsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApiInterface
     */
    listTenantJobs(requestParameters: AdminJobsApiListTenantJobsRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for getJob operation in AdminJobsApi.
 * @export
 * @interface AdminJobsApiGetJobRequest
 */
export interface AdminJobsApiGetJobRequest {
    /**
     * Job identifier
     * @type {number}
     * @memberof AdminJobsApiGetJob
     */
    readonly jobId: number
}

/**
 * Request parameters for getJobEvents operation in AdminJobsApi.
 * @export
 * @interface AdminJobsApiGetJobEventsRequest
 */
export interface AdminJobsApiGetJobEventsRequest {
    /**
     * Job identifier
     * @type {number}
     * @memberof AdminJobsApiGetJobEvents
     */
    readonly jobId: number
}

/**
 * Request parameters for getJobResults operation in AdminJobsApi.
 * @export
 * @interface AdminJobsApiGetJobResultsRequest
 */
export interface AdminJobsApiGetJobResultsRequest {
    /**
     * Job identifier
     * @type {number}
     * @memberof AdminJobsApiGetJobResults
     */
    readonly jobId: number
}

/**
 * Request parameters for listTenantJobs operation in AdminJobsApi.
 * @export
 * @interface AdminJobsApiListTenantJobsRequest
 */
export interface AdminJobsApiListTenantJobsRequest {
    /**
     * Tenant identifier
     * @type {string}
     * @memberof AdminJobsApiListTenantJobs
     */
    readonly tenantId: string
}

/**
 * AdminJobsApi - object-oriented interface
 * @export
 * @class AdminJobsApi
 * @extends {BaseAPI}
 */
export class AdminJobsApi extends BaseAPI implements AdminJobsApiInterface {
    /**
     * Fetch a single job.
     * @summary GET /v1/admin/jobs/{job_id}
     * @param {AdminJobsApiGetJobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApi
     */
    public getJob(requestParameters: AdminJobsApiGetJobRequest, options?: RawAxiosRequestConfig) {
        return AdminJobsApiFp(this.configuration).getJob(requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch events for a job.
     * @summary GET /v1/admin/jobs/{job_id}/events
     * @param {AdminJobsApiGetJobEventsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApi
     */
    public getJobEvents(requestParameters: AdminJobsApiGetJobEventsRequest, options?: RawAxiosRequestConfig) {
        return AdminJobsApiFp(this.configuration).getJobEvents(requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch task results for a job.
     * @summary GET /v1/admin/jobs/{job_id}/results
     * @param {AdminJobsApiGetJobResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApi
     */
    public getJobResults(requestParameters: AdminJobsApiGetJobResultsRequest, options?: RawAxiosRequestConfig) {
        return AdminJobsApiFp(this.configuration).getJobResults(requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List jobs across all tenants with optional filters.
     * @summary GET /v1/admin/jobs
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApi
     */
    public listJobs(options?: RawAxiosRequestConfig) {
        return AdminJobsApiFp(this.configuration).listJobs(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List jobs scoped to one tenant.
     * @summary GET /v1/admin/tenants/{tenant_id}/jobs
     * @param {AdminJobsApiListTenantJobsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminJobsApi
     */
    public listTenantJobs(requestParameters: AdminJobsApiListTenantJobsRequest, options?: RawAxiosRequestConfig) {
        return AdminJobsApiFp(this.configuration).listTenantJobs(requestParameters.tenantId, options).then((request) => request(this.axios, this.basePath));
    }
}

