/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CheckEmailOutput } from '../models';
// @ts-ignore
import type { CheckEmailRequest } from '../models';
// @ts-ignore
import type { GetV1Bulk200Response } from '../models';
// @ts-ignore
import type { GetV1BulkResults200Response } from '../models';
// @ts-ignore
import type { PostV1Bulk200Response } from '../models';
// @ts-ignore
import type { PostV1BulkRequest } from '../models';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieve the progress of a bulk verification job.
         * @summary /v1/bulk/{job_id}
         * @param {number} jobId The unique bulk verification job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1Bulk: async (jobId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getV1Bulk', 'jobId', jobId)
            const localVarPath = `/v1/bulk/{job_id}`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieve the results of a bulk verification job. This endpoint will return an error if the job is still running. Please query `GET /v1/bulk/{job_id}` first to check the job\'s progress.
         * @summary Retrieve bulk verification results
         * @param {string} jobId The unique bulk verification job ID
         * @param {number} [limit] The number of results to return.
         * @param {number} [offset] The offset from which to return the results, equivalent to the number of elements in the array to skip.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1BulkResults: async (jobId: string, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobId' is not null or undefined
            assertParamExists('getV1BulkResults', 'jobId', jobId)
            const localVarPath = `/v1/bulk/{job_id}/results`
                .replace(`{${"job_id"}}`, encodeURIComponent(String(jobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }



            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * **Sunset notice: please use `/v1/check_email` instead.** Both endpoints accept the same input arguments and return the same output; only their internal implementation differs. Perform a comprehensive verification of an email address. Unlike the `/v1/check_email` endpoint, this endpoint performs an email verification immediately, without considering the Reacher server\'s throttling, concurrency, and other configurations. As such, this endpoint is slightly riskier than `/v1/check_email`, as the Reacher server\'s IP reputation can be impacted if this endpoint is called too frequently.
         * @summary /v0/check_email
         * @param {string} authorization Your personal Reacher API key
         * @param {CheckEmailRequest} [checkEmailRequest] Request object containing all parameters necessary for an email verification.
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        postV0CheckEmail: async (authorization: string, checkEmailRequest?: CheckEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            assertParamExists('postV0CheckEmail', 'authorization', authorization)
            const localVarPath = `/v0/check_email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (authorization != null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initiate a bulk email verification.
         * @summary /v1/bulk
         * @param {PostV1BulkRequest} [postV1BulkRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1Bulk: async (postV1BulkRequest?: PostV1BulkRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/bulk`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postV1BulkRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Perform a comprehensive verification of an email address. This endpoint supersedes the previous `/v0/check_email` endpoint, maintaining the same input and output format. Unlike the `/v0/check_email` endpoint, the new `/v1/check_email` endpoint queues the email for verification, and the Reacher server processes the queue based on its configuration settings such as throttle and concurrency.
         * @summary /v1/check_email
         * @param {CheckEmailRequest} [checkEmailRequest] Request object containing all parameters necessary for an email verification.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1CheckEmail: async (checkEmailRequest?: CheckEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/check_email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)



            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieve the progress of a bulk verification job.
         * @summary /v1/bulk/{job_id}
         * @param {number} jobId The unique bulk verification job ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1Bulk(jobId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetV1Bulk200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1Bulk(jobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getV1Bulk']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieve the results of a bulk verification job. This endpoint will return an error if the job is still running. Please query `GET /v1/bulk/{job_id}` first to check the job\'s progress.
         * @summary Retrieve bulk verification results
         * @param {string} jobId The unique bulk verification job ID
         * @param {number} [limit] The number of results to return.
         * @param {number} [offset] The offset from which to return the results, equivalent to the number of elements in the array to skip.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getV1BulkResults(jobId: string, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetV1BulkResults200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getV1BulkResults(jobId, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getV1BulkResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * **Sunset notice: please use `/v1/check_email` instead.** Both endpoints accept the same input arguments and return the same output; only their internal implementation differs. Perform a comprehensive verification of an email address. Unlike the `/v1/check_email` endpoint, this endpoint performs an email verification immediately, without considering the Reacher server\'s throttling, concurrency, and other configurations. As such, this endpoint is slightly riskier than `/v1/check_email`, as the Reacher server\'s IP reputation can be impacted if this endpoint is called too frequently.
         * @summary /v0/check_email
         * @param {string} authorization Your personal Reacher API key
         * @param {CheckEmailRequest} [checkEmailRequest] Request object containing all parameters necessary for an email verification.
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async postV0CheckEmail(authorization: string, checkEmailRequest?: CheckEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmailOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV0CheckEmail(authorization, checkEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postV0CheckEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initiate a bulk email verification.
         * @summary /v1/bulk
         * @param {PostV1BulkRequest} [postV1BulkRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1Bulk(postV1BulkRequest?: PostV1BulkRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostV1Bulk200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1Bulk(postV1BulkRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postV1Bulk']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Perform a comprehensive verification of an email address. This endpoint supersedes the previous `/v0/check_email` endpoint, maintaining the same input and output format. Unlike the `/v0/check_email` endpoint, the new `/v1/check_email` endpoint queues the email for verification, and the Reacher server processes the queue based on its configuration settings such as throttle and concurrency.
         * @summary /v1/check_email
         * @param {CheckEmailRequest} [checkEmailRequest] Request object containing all parameters necessary for an email verification.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postV1CheckEmail(checkEmailRequest?: CheckEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckEmailOutput>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postV1CheckEmail(checkEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.postV1CheckEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Retrieve the progress of a bulk verification job.
         * @summary /v1/bulk/{job_id}
         * @param {DefaultApiGetV1BulkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1Bulk(requestParameters: DefaultApiGetV1BulkRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetV1Bulk200Response> {
            return localVarFp.getV1Bulk(requestParameters.jobId, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieve the results of a bulk verification job. This endpoint will return an error if the job is still running. Please query `GET /v1/bulk/{job_id}` first to check the job\'s progress.
         * @summary Retrieve bulk verification results
         * @param {DefaultApiGetV1BulkResultsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getV1BulkResults(requestParameters: DefaultApiGetV1BulkResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetV1BulkResults200Response> {
            return localVarFp.getV1BulkResults(requestParameters.jobId, requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * **Sunset notice: please use `/v1/check_email` instead.** Both endpoints accept the same input arguments and return the same output; only their internal implementation differs. Perform a comprehensive verification of an email address. Unlike the `/v1/check_email` endpoint, this endpoint performs an email verification immediately, without considering the Reacher server\'s throttling, concurrency, and other configurations. As such, this endpoint is slightly riskier than `/v1/check_email`, as the Reacher server\'s IP reputation can be impacted if this endpoint is called too frequently.
         * @summary /v0/check_email
         * @param {DefaultApiPostV0CheckEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        postV0CheckEmail(requestParameters: DefaultApiPostV0CheckEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailOutput> {
            return localVarFp.postV0CheckEmail(requestParameters.authorization, requestParameters.checkEmailRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Initiate a bulk email verification.
         * @summary /v1/bulk
         * @param {DefaultApiPostV1BulkRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1Bulk(requestParameters: DefaultApiPostV1BulkRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<PostV1Bulk200Response> {
            return localVarFp.postV1Bulk(requestParameters.postV1BulkRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Perform a comprehensive verification of an email address. This endpoint supersedes the previous `/v0/check_email` endpoint, maintaining the same input and output format. Unlike the `/v0/check_email` endpoint, the new `/v1/check_email` endpoint queues the email for verification, and the Reacher server processes the queue based on its configuration settings such as throttle and concurrency.
         * @summary /v1/check_email
         * @param {DefaultApiPostV1CheckEmailRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postV1CheckEmail(requestParameters: DefaultApiPostV1CheckEmailRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailOutput> {
            return localVarFp.postV1CheckEmail(requestParameters.checkEmailRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - interface
 * @export
 * @interface DefaultApi
 */
export interface DefaultApiInterface {
    /**
     * Retrieve the progress of a bulk verification job.
     * @summary /v1/bulk/{job_id}
     * @param {DefaultApiGetV1BulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getV1Bulk(requestParameters: DefaultApiGetV1BulkRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetV1Bulk200Response>;

    /**
     * Retrieve the results of a bulk verification job. This endpoint will return an error if the job is still running. Please query `GET /v1/bulk/{job_id}` first to check the job\'s progress.
     * @summary Retrieve bulk verification results
     * @param {DefaultApiGetV1BulkResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    getV1BulkResults(requestParameters: DefaultApiGetV1BulkResultsRequest, options?: RawAxiosRequestConfig): AxiosPromise<GetV1BulkResults200Response>;

    /**
     * **Sunset notice: please use `/v1/check_email` instead.** Both endpoints accept the same input arguments and return the same output; only their internal implementation differs. Perform a comprehensive verification of an email address. Unlike the `/v1/check_email` endpoint, this endpoint performs an email verification immediately, without considering the Reacher server\'s throttling, concurrency, and other configurations. As such, this endpoint is slightly riskier than `/v1/check_email`, as the Reacher server\'s IP reputation can be impacted if this endpoint is called too frequently.
     * @summary /v0/check_email
     * @param {DefaultApiPostV0CheckEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postV0CheckEmail(requestParameters: DefaultApiPostV0CheckEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailOutput>;

    /**
     * Initiate a bulk email verification.
     * @summary /v1/bulk
     * @param {DefaultApiPostV1BulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postV1Bulk(requestParameters?: DefaultApiPostV1BulkRequest, options?: RawAxiosRequestConfig): AxiosPromise<PostV1Bulk200Response>;

    /**
     * Perform a comprehensive verification of an email address. This endpoint supersedes the previous `/v0/check_email` endpoint, maintaining the same input and output format. Unlike the `/v0/check_email` endpoint, the new `/v1/check_email` endpoint queues the email for verification, and the Reacher server processes the queue based on its configuration settings such as throttle and concurrency.
     * @summary /v1/check_email
     * @param {DefaultApiPostV1CheckEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApiInterface
     */
    postV1CheckEmail(requestParameters?: DefaultApiPostV1CheckEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<CheckEmailOutput>;

}

/**
 * Request parameters for getV1Bulk operation in DefaultApi.
 * @export
 * @interface DefaultApiGetV1BulkRequest
 */
export interface DefaultApiGetV1BulkRequest {
    /**
     * The unique bulk verification job ID
     * @type {number}
     * @memberof DefaultApiGetV1Bulk
     */
    readonly jobId: number
}

/**
 * Request parameters for getV1BulkResults operation in DefaultApi.
 * @export
 * @interface DefaultApiGetV1BulkResultsRequest
 */
export interface DefaultApiGetV1BulkResultsRequest {
    /**
     * The unique bulk verification job ID
     * @type {string}
     * @memberof DefaultApiGetV1BulkResults
     */
    readonly jobId: string

    /**
     * The number of results to return.
     * @type {number}
     * @memberof DefaultApiGetV1BulkResults
     */
    readonly limit?: number

    /**
     * The offset from which to return the results, equivalent to the number of elements in the array to skip.
     * @type {number}
     * @memberof DefaultApiGetV1BulkResults
     */
    readonly offset?: number
}

/**
 * Request parameters for postV0CheckEmail operation in DefaultApi.
 * @export
 * @interface DefaultApiPostV0CheckEmailRequest
 */
export interface DefaultApiPostV0CheckEmailRequest {
    /**
     * Your personal Reacher API key
     * @type {string}
     * @memberof DefaultApiPostV0CheckEmail
     */
    readonly authorization: string

    /**
     * Request object containing all parameters necessary for an email verification.
     * @type {CheckEmailRequest}
     * @memberof DefaultApiPostV0CheckEmail
     */
    readonly checkEmailRequest?: CheckEmailRequest
}

/**
 * Request parameters for postV1Bulk operation in DefaultApi.
 * @export
 * @interface DefaultApiPostV1BulkRequest
 */
export interface DefaultApiPostV1BulkRequest {
    /**
     *
     * @type {PostV1BulkRequest}
     * @memberof DefaultApiPostV1Bulk
     */
    readonly postV1BulkRequest?: PostV1BulkRequest
}

/**
 * Request parameters for postV1CheckEmail operation in DefaultApi.
 * @export
 * @interface DefaultApiPostV1CheckEmailRequest
 */
export interface DefaultApiPostV1CheckEmailRequest {
    /**
     * Request object containing all parameters necessary for an email verification.
     * @type {CheckEmailRequest}
     * @memberof DefaultApiPostV1CheckEmail
     */
    readonly checkEmailRequest?: CheckEmailRequest
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI implements DefaultApiInterface {
    /**
     * Retrieve the progress of a bulk verification job.
     * @summary /v1/bulk/{job_id}
     * @param {DefaultApiGetV1BulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getV1Bulk(requestParameters: DefaultApiGetV1BulkRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getV1Bulk(requestParameters.jobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieve the results of a bulk verification job. This endpoint will return an error if the job is still running. Please query `GET /v1/bulk/{job_id}` first to check the job\'s progress.
     * @summary Retrieve bulk verification results
     * @param {DefaultApiGetV1BulkResultsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getV1BulkResults(requestParameters: DefaultApiGetV1BulkResultsRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getV1BulkResults(requestParameters.jobId, requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * **Sunset notice: please use `/v1/check_email` instead.** Both endpoints accept the same input arguments and return the same output; only their internal implementation differs. Perform a comprehensive verification of an email address. Unlike the `/v1/check_email` endpoint, this endpoint performs an email verification immediately, without considering the Reacher server\'s throttling, concurrency, and other configurations. As such, this endpoint is slightly riskier than `/v1/check_email`, as the Reacher server\'s IP reputation can be impacted if this endpoint is called too frequently.
     * @summary /v0/check_email
     * @param {DefaultApiPostV0CheckEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postV0CheckEmail(requestParameters: DefaultApiPostV0CheckEmailRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postV0CheckEmail(requestParameters.authorization, requestParameters.checkEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initiate a bulk email verification.
     * @summary /v1/bulk
     * @param {DefaultApiPostV1BulkRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postV1Bulk(requestParameters: DefaultApiPostV1BulkRequest = {}, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postV1Bulk(requestParameters.postV1BulkRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Perform a comprehensive verification of an email address. This endpoint supersedes the previous `/v0/check_email` endpoint, maintaining the same input and output format. Unlike the `/v0/check_email` endpoint, the new `/v1/check_email` endpoint queues the email for verification, and the Reacher server processes the queue based on its configuration settings such as throttle and concurrency.
     * @summary /v1/check_email
     * @param {DefaultApiPostV1CheckEmailRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public postV1CheckEmail(requestParameters: DefaultApiPostV1CheckEmailRequest = {}, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).postV1CheckEmail(requestParameters.checkEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
