/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreatePipelineInput } from '../models';
// @ts-ignore
import type { DeletePipelineResponse } from '../models';
// @ts-ignore
import type { ListPipelineRunsResponse } from '../models';
// @ts-ignore
import type { ListPipelinesResponse } from '../models';
// @ts-ignore
import type { PipelineErrorResponse } from '../models';
// @ts-ignore
import type { PipelineRunView } from '../models';
// @ts-ignore
import type { PipelineStatus } from '../models';
// @ts-ignore
import type { PipelineView } from '../models';
// @ts-ignore
import type { TriggerPipelineInput } from '../models';
// @ts-ignore
import type { TriggerPipelineResponse } from '../models';
// @ts-ignore
import type { UpdatePipelineInput } from '../models';
/**
 * PipelinesApi - axios parameter creator
 * @export
 */
export const PipelinesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary POST /v1/pipelines
         * @param {CreatePipelineInput} createPipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CreatePipeline: async (createPipelineInput: CreatePipelineInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createPipelineInput' is not null or undefined
            assertParamExists('v1CreatePipeline', 'createPipelineInput', createPipelineInput)
            const localVarPath = `/v1/pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createPipelineInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary DELETE /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1DeletePipeline: async (pipelineId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1DeletePipeline', 'pipelineId', pipelineId)
            const localVarPath = `/v1/pipelines/{pipeline_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetPipeline: async (pipelineId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1GetPipeline', 'pipelineId', pipelineId)
            const localVarPath = `/v1/pipelines/{pipeline_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs/{run_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {number} runId Pipeline run identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetPipelineRun: async (pipelineId: number, runId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1GetPipelineRun', 'pipelineId', pipelineId)
            // verify required parameter 'runId' is not null or undefined
            assertParamExists('v1GetPipelineRun', 'runId', runId)
            const localVarPath = `/v1/pipelines/{pipeline_id}/runs/{run_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)))
                .replace(`{${"run_id"}}`, encodeURIComponent(String(runId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs
         * @param {number} pipelineId Pipeline identifier
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListPipelineRuns: async (pipelineId: number, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1ListPipelineRuns', 'pipelineId', pipelineId)
            const localVarPath = `/v1/pipelines/{pipeline_id}/runs`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /v1/pipelines
         * @param {PipelineStatus} [status] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListPipelines: async (status?: PipelineStatus, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/pipelines`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/pause
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1PausePipeline: async (pipelineId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1PausePipeline', 'pipelineId', pipelineId)
            const localVarPath = `/v1/pipelines/{pipeline_id}/pause`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/resume
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ResumePipeline: async (pipelineId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1ResumePipeline', 'pipelineId', pipelineId)
            const localVarPath = `/v1/pipelines/{pipeline_id}/resume`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/trigger
         * @param {number} pipelineId Pipeline identifier
         * @param {TriggerPipelineInput} triggerPipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1TriggerPipeline: async (pipelineId: number, triggerPipelineInput: TriggerPipelineInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1TriggerPipeline', 'pipelineId', pipelineId)
            // verify required parameter 'triggerPipelineInput' is not null or undefined
            assertParamExists('v1TriggerPipeline', 'triggerPipelineInput', triggerPipelineInput)
            const localVarPath = `/v1/pipelines/{pipeline_id}/trigger`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(triggerPipelineInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary PATCH /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {UpdatePipelineInput} updatePipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdatePipeline: async (pipelineId: number, updatePipelineInput: UpdatePipelineInput, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pipelineId' is not null or undefined
            assertParamExists('v1UpdatePipeline', 'pipelineId', pipelineId)
            // verify required parameter 'updatePipelineInput' is not null or undefined
            assertParamExists('v1UpdatePipeline', 'updatePipelineInput', updatePipelineInput)
            const localVarPath = `/v1/pipelines/{pipeline_id}`
                .replace(`{${"pipeline_id"}}`, encodeURIComponent(String(pipelineId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updatePipelineInput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PipelinesApi - functional programming interface
 * @export
 */
export const PipelinesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PipelinesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary POST /v1/pipelines
         * @param {CreatePipelineInput} createPipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1CreatePipeline(createPipelineInput: CreatePipelineInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1CreatePipeline(createPipelineInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1CreatePipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary DELETE /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1DeletePipeline(pipelineId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeletePipelineResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1DeletePipeline(pipelineId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1DeletePipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetPipeline(pipelineId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetPipeline(pipelineId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1GetPipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs/{run_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {number} runId Pipeline run identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetPipelineRun(pipelineId: number, runId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineRunView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetPipelineRun(pipelineId, runId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1GetPipelineRun']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs
         * @param {number} pipelineId Pipeline identifier
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ListPipelineRuns(pipelineId: number, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPipelineRunsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ListPipelineRuns(pipelineId, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1ListPipelineRuns']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /v1/pipelines
         * @param {PipelineStatus} [status] 
         * @param {number} [limit] 
         * @param {number} [offset] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ListPipelines(status?: PipelineStatus, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPipelinesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ListPipelines(status, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1ListPipelines']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/pause
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1PausePipeline(pipelineId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1PausePipeline(pipelineId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1PausePipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/resume
         * @param {number} pipelineId Pipeline identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ResumePipeline(pipelineId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ResumePipeline(pipelineId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1ResumePipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/trigger
         * @param {number} pipelineId Pipeline identifier
         * @param {TriggerPipelineInput} triggerPipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1TriggerPipeline(pipelineId: number, triggerPipelineInput: TriggerPipelineInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TriggerPipelineResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1TriggerPipeline(pipelineId, triggerPipelineInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1TriggerPipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary PATCH /v1/pipelines/{pipeline_id}
         * @param {number} pipelineId Pipeline identifier
         * @param {UpdatePipelineInput} updatePipelineInput 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UpdatePipeline(pipelineId: number, updatePipelineInput: UpdatePipelineInput, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PipelineView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UpdatePipeline(pipelineId, updatePipelineInput, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PipelinesApi.v1UpdatePipeline']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PipelinesApi - factory interface
 * @export
 */
export const PipelinesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PipelinesApiFp(configuration)
    return {
        /**
         * 
         * @summary POST /v1/pipelines
         * @param {PipelinesApiV1CreatePipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CreatePipeline(requestParameters: PipelinesApiV1CreatePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView> {
            return localVarFp.v1CreatePipeline(requestParameters.createPipelineInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary DELETE /v1/pipelines/{pipeline_id}
         * @param {PipelinesApiV1DeletePipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1DeletePipeline(requestParameters: PipelinesApiV1DeletePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletePipelineResponse> {
            return localVarFp.v1DeletePipeline(requestParameters.pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}
         * @param {PipelinesApiV1GetPipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetPipeline(requestParameters: PipelinesApiV1GetPipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView> {
            return localVarFp.v1GetPipeline(requestParameters.pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs/{run_id}
         * @param {PipelinesApiV1GetPipelineRunRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetPipelineRun(requestParameters: PipelinesApiV1GetPipelineRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineRunView> {
            return localVarFp.v1GetPipelineRun(requestParameters.pipelineId, requestParameters.runId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /v1/pipelines/{pipeline_id}/runs
         * @param {PipelinesApiV1ListPipelineRunsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListPipelineRuns(requestParameters: PipelinesApiV1ListPipelineRunsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListPipelineRunsResponse> {
            return localVarFp.v1ListPipelineRuns(requestParameters.pipelineId, requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /v1/pipelines
         * @param {PipelinesApiV1ListPipelinesRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListPipelines(requestParameters: PipelinesApiV1ListPipelinesRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListPipelinesResponse> {
            return localVarFp.v1ListPipelines(requestParameters.status, requestParameters.limit, requestParameters.offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/pause
         * @param {PipelinesApiV1PausePipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1PausePipeline(requestParameters: PipelinesApiV1PausePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView> {
            return localVarFp.v1PausePipeline(requestParameters.pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/resume
         * @param {PipelinesApiV1ResumePipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ResumePipeline(requestParameters: PipelinesApiV1ResumePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView> {
            return localVarFp.v1ResumePipeline(requestParameters.pipelineId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary POST /v1/pipelines/{pipeline_id}/trigger
         * @param {PipelinesApiV1TriggerPipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1TriggerPipeline(requestParameters: PipelinesApiV1TriggerPipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<TriggerPipelineResponse> {
            return localVarFp.v1TriggerPipeline(requestParameters.pipelineId, requestParameters.triggerPipelineInput, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary PATCH /v1/pipelines/{pipeline_id}
         * @param {PipelinesApiV1UpdatePipelineRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdatePipeline(requestParameters: PipelinesApiV1UpdatePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView> {
            return localVarFp.v1UpdatePipeline(requestParameters.pipelineId, requestParameters.updatePipelineInput, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PipelinesApi - interface
 * @export
 * @interface PipelinesApi
 */
export interface PipelinesApiInterface {
    /**
     * 
     * @summary POST /v1/pipelines
     * @param {PipelinesApiV1CreatePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1CreatePipeline(requestParameters: PipelinesApiV1CreatePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView>;

    /**
     * 
     * @summary DELETE /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1DeletePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1DeletePipeline(requestParameters: PipelinesApiV1DeletePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeletePipelineResponse>;

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1GetPipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1GetPipeline(requestParameters: PipelinesApiV1GetPipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView>;

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}/runs/{run_id}
     * @param {PipelinesApiV1GetPipelineRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1GetPipelineRun(requestParameters: PipelinesApiV1GetPipelineRunRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineRunView>;

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}/runs
     * @param {PipelinesApiV1ListPipelineRunsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1ListPipelineRuns(requestParameters: PipelinesApiV1ListPipelineRunsRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListPipelineRunsResponse>;

    /**
     * 
     * @summary GET /v1/pipelines
     * @param {PipelinesApiV1ListPipelinesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1ListPipelines(requestParameters?: PipelinesApiV1ListPipelinesRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListPipelinesResponse>;

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/pause
     * @param {PipelinesApiV1PausePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1PausePipeline(requestParameters: PipelinesApiV1PausePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView>;

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/resume
     * @param {PipelinesApiV1ResumePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1ResumePipeline(requestParameters: PipelinesApiV1ResumePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView>;

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/trigger
     * @param {PipelinesApiV1TriggerPipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1TriggerPipeline(requestParameters: PipelinesApiV1TriggerPipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<TriggerPipelineResponse>;

    /**
     * 
     * @summary PATCH /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1UpdatePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApiInterface
     */
    v1UpdatePipeline(requestParameters: PipelinesApiV1UpdatePipelineRequest, options?: RawAxiosRequestConfig): AxiosPromise<PipelineView>;

}

/**
 * Request parameters for v1CreatePipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1CreatePipelineRequest
 */
export interface PipelinesApiV1CreatePipelineRequest {
    /**
     * 
     * @type {CreatePipelineInput}
     * @memberof PipelinesApiV1CreatePipeline
     */
    readonly createPipelineInput: CreatePipelineInput
}

/**
 * Request parameters for v1DeletePipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1DeletePipelineRequest
 */
export interface PipelinesApiV1DeletePipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1DeletePipeline
     */
    readonly pipelineId: number
}

/**
 * Request parameters for v1GetPipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1GetPipelineRequest
 */
export interface PipelinesApiV1GetPipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1GetPipeline
     */
    readonly pipelineId: number
}

/**
 * Request parameters for v1GetPipelineRun operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1GetPipelineRunRequest
 */
export interface PipelinesApiV1GetPipelineRunRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1GetPipelineRun
     */
    readonly pipelineId: number

    /**
     * Pipeline run identifier
     * @type {number}
     * @memberof PipelinesApiV1GetPipelineRun
     */
    readonly runId: number
}

/**
 * Request parameters for v1ListPipelineRuns operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1ListPipelineRunsRequest
 */
export interface PipelinesApiV1ListPipelineRunsRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1ListPipelineRuns
     */
    readonly pipelineId: number

    /**
     * 
     * @type {number}
     * @memberof PipelinesApiV1ListPipelineRuns
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof PipelinesApiV1ListPipelineRuns
     */
    readonly offset?: number
}

/**
 * Request parameters for v1ListPipelines operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1ListPipelinesRequest
 */
export interface PipelinesApiV1ListPipelinesRequest {
    /**
     * 
     * @type {PipelineStatus}
     * @memberof PipelinesApiV1ListPipelines
     */
    readonly status?: PipelineStatus

    /**
     * 
     * @type {number}
     * @memberof PipelinesApiV1ListPipelines
     */
    readonly limit?: number

    /**
     * 
     * @type {number}
     * @memberof PipelinesApiV1ListPipelines
     */
    readonly offset?: number
}

/**
 * Request parameters for v1PausePipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1PausePipelineRequest
 */
export interface PipelinesApiV1PausePipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1PausePipeline
     */
    readonly pipelineId: number
}

/**
 * Request parameters for v1ResumePipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1ResumePipelineRequest
 */
export interface PipelinesApiV1ResumePipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1ResumePipeline
     */
    readonly pipelineId: number
}

/**
 * Request parameters for v1TriggerPipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1TriggerPipelineRequest
 */
export interface PipelinesApiV1TriggerPipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1TriggerPipeline
     */
    readonly pipelineId: number

    /**
     * 
     * @type {TriggerPipelineInput}
     * @memberof PipelinesApiV1TriggerPipeline
     */
    readonly triggerPipelineInput: TriggerPipelineInput
}

/**
 * Request parameters for v1UpdatePipeline operation in PipelinesApi.
 * @export
 * @interface PipelinesApiV1UpdatePipelineRequest
 */
export interface PipelinesApiV1UpdatePipelineRequest {
    /**
     * Pipeline identifier
     * @type {number}
     * @memberof PipelinesApiV1UpdatePipeline
     */
    readonly pipelineId: number

    /**
     * 
     * @type {UpdatePipelineInput}
     * @memberof PipelinesApiV1UpdatePipeline
     */
    readonly updatePipelineInput: UpdatePipelineInput
}

/**
 * PipelinesApi - object-oriented interface
 * @export
 * @class PipelinesApi
 * @extends {BaseAPI}
 */
export class PipelinesApi extends BaseAPI implements PipelinesApiInterface {
    /**
     * 
     * @summary POST /v1/pipelines
     * @param {PipelinesApiV1CreatePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1CreatePipeline(requestParameters: PipelinesApiV1CreatePipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1CreatePipeline(requestParameters.createPipelineInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary DELETE /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1DeletePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1DeletePipeline(requestParameters: PipelinesApiV1DeletePipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1DeletePipeline(requestParameters.pipelineId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1GetPipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1GetPipeline(requestParameters: PipelinesApiV1GetPipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1GetPipeline(requestParameters.pipelineId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}/runs/{run_id}
     * @param {PipelinesApiV1GetPipelineRunRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1GetPipelineRun(requestParameters: PipelinesApiV1GetPipelineRunRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1GetPipelineRun(requestParameters.pipelineId, requestParameters.runId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /v1/pipelines/{pipeline_id}/runs
     * @param {PipelinesApiV1ListPipelineRunsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1ListPipelineRuns(requestParameters: PipelinesApiV1ListPipelineRunsRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1ListPipelineRuns(requestParameters.pipelineId, requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /v1/pipelines
     * @param {PipelinesApiV1ListPipelinesRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1ListPipelines(requestParameters: PipelinesApiV1ListPipelinesRequest = {}, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1ListPipelines(requestParameters.status, requestParameters.limit, requestParameters.offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/pause
     * @param {PipelinesApiV1PausePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1PausePipeline(requestParameters: PipelinesApiV1PausePipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1PausePipeline(requestParameters.pipelineId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/resume
     * @param {PipelinesApiV1ResumePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1ResumePipeline(requestParameters: PipelinesApiV1ResumePipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1ResumePipeline(requestParameters.pipelineId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary POST /v1/pipelines/{pipeline_id}/trigger
     * @param {PipelinesApiV1TriggerPipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1TriggerPipeline(requestParameters: PipelinesApiV1TriggerPipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1TriggerPipeline(requestParameters.pipelineId, requestParameters.triggerPipelineInput, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary PATCH /v1/pipelines/{pipeline_id}
     * @param {PipelinesApiV1UpdatePipelineRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PipelinesApi
     */
    public v1UpdatePipeline(requestParameters: PipelinesApiV1UpdatePipelineRequest, options?: RawAxiosRequestConfig) {
        return PipelinesApiFp(this.configuration).v1UpdatePipeline(requestParameters.pipelineId, requestParameters.updatePipelineInput, options).then((request) => request(this.axios, this.basePath));
    }
}

