/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * TenantApi - axios parameter creator
 * @export
 */
export const TenantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Clear tenant webhook URL and signing secret.
         * @summary DELETE /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ClearTenantWebhook: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/webhook`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Add a domain for the authenticated tenant.
         * @summary POST /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CreateTenantDomain: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a domain from the authenticated tenant.
         * @summary DELETE /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1DeleteTenantDomain: async (domain: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('v1DeleteTenantDomain', 'domain', domain)
            const localVarPath = `/v1/me/domains/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get one domain entry for the authenticated tenant.
         * @summary GET /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantDomain: async (domain: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('v1GetTenantDomain', 'domain', domain)
            const localVarPath = `/v1/me/domains/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get tenant runtime settings and default operational behavior.
         * @summary GET /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantSettings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Return current tenant usage and quota summary.
         * @summary GET /v1/me/usage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantUsage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/usage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get masked tenant webhook integration state.
         * @summary GET /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantWebhook: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/webhook`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * List all active and inactive domain entries for the authenticated tenant.
         * @summary GET /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListTenantDomains: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/domains`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update the domain value, status, verification state, or metadata notes.
         * @summary PATCH /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantDomain: async (domain: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'domain' is not null or undefined
            assertParamExists('v1UpdateTenantDomain', 'domain', domain)
            const localVarPath = `/v1/me/domains/{domain}`
                .replace(`{${"domain"}}`, encodeURIComponent(String(domain)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update tenant settings such as retention, default webhook URL, or secret.
         * @summary PATCH /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantSettings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/settings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update tenant webhook URL and signing secret.
         * @summary PATCH /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantWebhook: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/me/webhook`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TenantApi - functional programming interface
 * @export
 */
export const TenantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TenantApiAxiosParamCreator(configuration)
    return {
        /**
         * Clear tenant webhook URL and signing secret.
         * @summary DELETE /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ClearTenantWebhook(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ClearTenantWebhook(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1ClearTenantWebhook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Add a domain for the authenticated tenant.
         * @summary POST /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1CreateTenantDomain(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1CreateTenantDomain(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1CreateTenantDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Remove a domain from the authenticated tenant.
         * @summary DELETE /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1DeleteTenantDomain(domain: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1DeleteTenantDomain(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1DeleteTenantDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get one domain entry for the authenticated tenant.
         * @summary GET /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetTenantDomain(domain: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetTenantDomain(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1GetTenantDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get tenant runtime settings and default operational behavior.
         * @summary GET /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetTenantSettings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetTenantSettings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1GetTenantSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Return current tenant usage and quota summary.
         * @summary GET /v1/me/usage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetTenantUsage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetTenantUsage(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1GetTenantUsage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get masked tenant webhook integration state.
         * @summary GET /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1GetTenantWebhook(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1GetTenantWebhook(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1GetTenantWebhook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List all active and inactive domain entries for the authenticated tenant.
         * @summary GET /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1ListTenantDomains(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1ListTenantDomains(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1ListTenantDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update the domain value, status, verification state, or metadata notes.
         * @summary PATCH /v1/me/domains/{domain}
         * @param {string} domain Domain identifier
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UpdateTenantDomain(domain: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UpdateTenantDomain(domain, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1UpdateTenantDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update tenant settings such as retention, default webhook URL, or secret.
         * @summary PATCH /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UpdateTenantSettings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UpdateTenantSettings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1UpdateTenantSettings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update tenant webhook URL and signing secret.
         * @summary PATCH /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v1UpdateTenantWebhook(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v1UpdateTenantWebhook(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TenantApi.v1UpdateTenantWebhook']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TenantApi - factory interface
 * @export
 */
export const TenantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TenantApiFp(configuration)
    return {
        /**
         * Clear tenant webhook URL and signing secret.
         * @summary DELETE /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ClearTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ClearTenantWebhook(options).then((request) => request(axios, basePath));
        },
        /**
         * Add a domain for the authenticated tenant.
         * @summary POST /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1CreateTenantDomain(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1CreateTenantDomain(options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a domain from the authenticated tenant.
         * @summary DELETE /v1/me/domains/{domain}
         * @param {TenantApiV1DeleteTenantDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1DeleteTenantDomain(requestParameters: TenantApiV1DeleteTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1DeleteTenantDomain(requestParameters.domain, options).then((request) => request(axios, basePath));
        },
        /**
         * Get one domain entry for the authenticated tenant.
         * @summary GET /v1/me/domains/{domain}
         * @param {TenantApiV1GetTenantDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantDomain(requestParameters: TenantApiV1GetTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1GetTenantDomain(requestParameters.domain, options).then((request) => request(axios, basePath));
        },
        /**
         * Get tenant runtime settings and default operational behavior.
         * @summary GET /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantSettings(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1GetTenantSettings(options).then((request) => request(axios, basePath));
        },
        /**
         * Return current tenant usage and quota summary.
         * @summary GET /v1/me/usage
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantUsage(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1GetTenantUsage(options).then((request) => request(axios, basePath));
        },
        /**
         * Get masked tenant webhook integration state.
         * @summary GET /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1GetTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1GetTenantWebhook(options).then((request) => request(axios, basePath));
        },
        /**
         * List all active and inactive domain entries for the authenticated tenant.
         * @summary GET /v1/me/domains
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1ListTenantDomains(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1ListTenantDomains(options).then((request) => request(axios, basePath));
        },
        /**
         * Update the domain value, status, verification state, or metadata notes.
         * @summary PATCH /v1/me/domains/{domain}
         * @param {TenantApiV1UpdateTenantDomainRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantDomain(requestParameters: TenantApiV1UpdateTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1UpdateTenantDomain(requestParameters.domain, options).then((request) => request(axios, basePath));
        },
        /**
         * Update tenant settings such as retention, default webhook URL, or secret.
         * @summary PATCH /v1/me/settings
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantSettings(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1UpdateTenantSettings(options).then((request) => request(axios, basePath));
        },
        /**
         * Update tenant webhook URL and signing secret.
         * @summary PATCH /v1/me/webhook
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v1UpdateTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.v1UpdateTenantWebhook(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TenantApi - interface
 * @export
 * @interface TenantApi
 */
export interface TenantApiInterface {
    /**
     * Clear tenant webhook URL and signing secret.
     * @summary DELETE /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1ClearTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Add a domain for the authenticated tenant.
     * @summary POST /v1/me/domains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1CreateTenantDomain(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Remove a domain from the authenticated tenant.
     * @summary DELETE /v1/me/domains/{domain}
     * @param {TenantApiV1DeleteTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1DeleteTenantDomain(requestParameters: TenantApiV1DeleteTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get one domain entry for the authenticated tenant.
     * @summary GET /v1/me/domains/{domain}
     * @param {TenantApiV1GetTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1GetTenantDomain(requestParameters: TenantApiV1GetTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get tenant runtime settings and default operational behavior.
     * @summary GET /v1/me/settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1GetTenantSettings(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Return current tenant usage and quota summary.
     * @summary GET /v1/me/usage
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1GetTenantUsage(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Get masked tenant webhook integration state.
     * @summary GET /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1GetTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * List all active and inactive domain entries for the authenticated tenant.
     * @summary GET /v1/me/domains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1ListTenantDomains(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Update the domain value, status, verification state, or metadata notes.
     * @summary PATCH /v1/me/domains/{domain}
     * @param {TenantApiV1UpdateTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1UpdateTenantDomain(requestParameters: TenantApiV1UpdateTenantDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Update tenant settings such as retention, default webhook URL, or secret.
     * @summary PATCH /v1/me/settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1UpdateTenantSettings(options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Update tenant webhook URL and signing secret.
     * @summary PATCH /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApiInterface
     */
    v1UpdateTenantWebhook(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * Request parameters for v1DeleteTenantDomain operation in TenantApi.
 * @export
 * @interface TenantApiV1DeleteTenantDomainRequest
 */
export interface TenantApiV1DeleteTenantDomainRequest {
    /**
     * Domain identifier
     * @type {string}
     * @memberof TenantApiV1DeleteTenantDomain
     */
    readonly domain: string
}

/**
 * Request parameters for v1GetTenantDomain operation in TenantApi.
 * @export
 * @interface TenantApiV1GetTenantDomainRequest
 */
export interface TenantApiV1GetTenantDomainRequest {
    /**
     * Domain identifier
     * @type {string}
     * @memberof TenantApiV1GetTenantDomain
     */
    readonly domain: string
}

/**
 * Request parameters for v1UpdateTenantDomain operation in TenantApi.
 * @export
 * @interface TenantApiV1UpdateTenantDomainRequest
 */
export interface TenantApiV1UpdateTenantDomainRequest {
    /**
     * Domain identifier
     * @type {string}
     * @memberof TenantApiV1UpdateTenantDomain
     */
    readonly domain: string
}

/**
 * TenantApi - object-oriented interface
 * @export
 * @class TenantApi
 * @extends {BaseAPI}
 */
export class TenantApi extends BaseAPI implements TenantApiInterface {
    /**
     * Clear tenant webhook URL and signing secret.
     * @summary DELETE /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1ClearTenantWebhook(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1ClearTenantWebhook(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Add a domain for the authenticated tenant.
     * @summary POST /v1/me/domains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1CreateTenantDomain(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1CreateTenantDomain(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Remove a domain from the authenticated tenant.
     * @summary DELETE /v1/me/domains/{domain}
     * @param {TenantApiV1DeleteTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1DeleteTenantDomain(requestParameters: TenantApiV1DeleteTenantDomainRequest, options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1DeleteTenantDomain(requestParameters.domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get one domain entry for the authenticated tenant.
     * @summary GET /v1/me/domains/{domain}
     * @param {TenantApiV1GetTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1GetTenantDomain(requestParameters: TenantApiV1GetTenantDomainRequest, options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1GetTenantDomain(requestParameters.domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get tenant runtime settings and default operational behavior.
     * @summary GET /v1/me/settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1GetTenantSettings(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1GetTenantSettings(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Return current tenant usage and quota summary.
     * @summary GET /v1/me/usage
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1GetTenantUsage(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1GetTenantUsage(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get masked tenant webhook integration state.
     * @summary GET /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1GetTenantWebhook(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1GetTenantWebhook(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List all active and inactive domain entries for the authenticated tenant.
     * @summary GET /v1/me/domains
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1ListTenantDomains(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1ListTenantDomains(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update the domain value, status, verification state, or metadata notes.
     * @summary PATCH /v1/me/domains/{domain}
     * @param {TenantApiV1UpdateTenantDomainRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1UpdateTenantDomain(requestParameters: TenantApiV1UpdateTenantDomainRequest, options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1UpdateTenantDomain(requestParameters.domain, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update tenant settings such as retention, default webhook URL, or secret.
     * @summary PATCH /v1/me/settings
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1UpdateTenantSettings(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1UpdateTenantSettings(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update tenant webhook URL and signing secret.
     * @summary PATCH /v1/me/webhook
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TenantApi
     */
    public v1UpdateTenantWebhook(options?: RawAxiosRequestConfig) {
        return TenantApiFp(this.configuration).v1UpdateTenantWebhook(options).then((request) => request(this.axios, this.basePath));
    }
}

