/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddSuppressionsResponse
 */
export interface AddSuppressionsResponse {
    /**
     * 
     * @type {number}
     * @memberof AddSuppressionsResponse
     */
    'added': number;
    /**
     * 
     * @type {number}
     * @memberof AddSuppressionsResponse
     */
    'duplicates': number;
}

