/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface AdminTenant
 */
export interface AdminTenant {
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'id'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'slug'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'contact_email'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'plan_tier'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'status'?: string;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'monthly_email_limit'?: number | null;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'max_requests_per_second'?: number;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'max_requests_per_minute'?: number;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'max_requests_per_hour'?: number;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'max_requests_per_day'?: number;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'used_this_period'?: number;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'default_webhook_url'?: string | null;
    /**
     *
     * @type {number}
     * @memberof AdminTenant
     */
    'result_retention_days'?: number;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'created_at'?: string;
    /**
     *
     * @type {string}
     * @memberof AdminTenant
     */
    'updated_at'?: string;
}
