/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ApprovalCategoryBreakdown } from './approval-category-breakdown';
// May contain unused imports in some cases
// @ts-ignore
import type { ApprovalRiskFlags } from './approval-risk-flags';

/**
 * 
 * @export
 * @interface ApprovalChecklistResponse
 */
export interface ApprovalChecklistResponse {
    /**
     * 
     * @type {ApprovalCategoryBreakdown}
     * @memberof ApprovalChecklistResponse
     */
    'categories': ApprovalCategoryBreakdown;
    /**
     * 
     * @type {number}
     * @memberof ApprovalChecklistResponse
     */
    'job_id': number;
    /**
     * 
     * @type {boolean}
     * @memberof ApprovalChecklistResponse
     */
    'ready_to_send': boolean;
    /**
     * 
     * @type {string}
     * @memberof ApprovalChecklistResponse
     */
    'recommendation': string;
    /**
     * 
     * @type {ApprovalRiskFlags}
     * @memberof ApprovalChecklistResponse
     */
    'risk_flags': ApprovalRiskFlags;
    /**
     * 
     * @type {number}
     * @memberof ApprovalChecklistResponse
     */
    'safe_to_send_count': number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalChecklistResponse
     */
    'safe_to_send_pct': number;
    /**
     * 
     * @type {number}
     * @memberof ApprovalChecklistResponse
     */
    'total_records': number;
}

