/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CoreError } from './core-error';
// May contain unused imports in some cases
// @ts-ignore
import type { SmtpDetails } from './smtp-details';

/**
 * @type CheckEmailOutputSmtp
 * Results from connecting to the mail server via SMTP.
 * @export
 */
export type CheckEmailOutputSmtp = CoreError | SmtpDetails;
