/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConfidenceExplanation
 */
export interface ConfidenceExplanation {
    /**
     * 
     * @type {Array<string>}
     * @memberof ConfidenceExplanation
     */
    'factors': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ConfidenceExplanation
     */
    'level': ConfidenceExplanationLevelEnum;
    /**
     * 
     * @type {number}
     * @memberof ConfidenceExplanation
     */
    'score': number;
}

export const ConfidenceExplanationLevelEnum = {
    High: 'high',
    Medium: 'medium',
    Low: 'low',
    VeryLow: 'very_low'
} as const;

export type ConfidenceExplanationLevelEnum = typeof ConfidenceExplanationLevelEnum[keyof typeof ConfidenceExplanationLevelEnum];


