/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     *
     * @type {string}
     * @memberof CreateCommentRequest
     */
    'author'?: string | null;
    /**
     *
     * @type {string}
     * @memberof CreateCommentRequest
     */
    'body': string;
    /**
     *
     * @type {number}
     * @memberof CreateCommentRequest
     */
    'job_id'?: number | null;
    /**
     *
     * @type {number}
     * @memberof CreateCommentRequest
     */
    'list_id'?: number | null;
}
