/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PipelineDeliveryConfig } from './pipeline-delivery-config';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelinePolicyConfig } from './pipeline-policy-config';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSchedule } from './pipeline-schedule';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSource } from './pipeline-source';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineStatus } from './pipeline-status';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineVerificationSettings } from './pipeline-verification-settings';

/**
 * 
 * @export
 * @interface CreatePipelineInput
 */
export interface CreatePipelineInput {
    /**
     * 
     * @type {PipelineDeliveryConfig}
     * @memberof CreatePipelineInput
     */
    'delivery'?: PipelineDeliveryConfig;
    /**
     * 
     * @type {string}
     * @memberof CreatePipelineInput
     */
    'name': string;
    /**
     * 
     * @type {PipelinePolicyConfig}
     * @memberof CreatePipelineInput
     */
    'policy'?: PipelinePolicyConfig;
    /**
     * 
     * @type {PipelineSchedule}
     * @memberof CreatePipelineInput
     */
    'schedule': PipelineSchedule;
    /**
     * 
     * @type {PipelineSource}
     * @memberof CreatePipelineInput
     */
    'source': PipelineSource;
    /**
     * 
     * @type {PipelineStatus}
     * @memberof CreatePipelineInput
     */
    'status'?: PipelineStatus;
    /**
     * 
     * @type {PipelineVerificationSettings}
     * @memberof CreatePipelineInput
     */
    'verification'?: PipelineVerificationSettings;
}



