/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CatchAllScore } from './catch-all-score';
// May contain unused imports in some cases
// @ts-ignore
import type { CatchAllSeverity } from './catch-all-severity';
// May contain unused imports in some cases
// @ts-ignore
import type { ConfidenceLevel } from './confidence-level';
// May contain unused imports in some cases
// @ts-ignore
import type { EmailCategory } from './email-category';
// May contain unused imports in some cases
// @ts-ignore
import type { Freshness } from './freshness';
// May contain unused imports in some cases
// @ts-ignore
import type { PartialConfidence } from './partial-confidence';
// May contain unused imports in some cases
// @ts-ignore
import type { ReasonCode } from './reason-code';
// May contain unused imports in some cases
// @ts-ignore
import type { ScoringSignals } from './scoring-signals';
// May contain unused imports in some cases
// @ts-ignore
import type { SubReason } from './sub-reason';

/**
 *
 * @export
 * @interface EmailScore
 */
export interface EmailScore {
    /**
     *
     * @type {number}
     * @memberof EmailScore
     */
    'age_days'?: number;
    /**
     *
     * @type {CatchAllScore}
     * @memberof EmailScore
     */
    'catch_all'?: CatchAllScore;
    /**
     *
     * @type {CatchAllSeverity}
     * @memberof EmailScore
     */
    'catch_all_severity'?: CatchAllSeverity;
    /**
     *
     * @type {EmailCategory}
     * @memberof EmailScore
     */
    'category': EmailCategory;
    /**
     *
     * @type {number}
     * @memberof EmailScore
     */
    'confidence'?: number;
    /**
     *
     * @type {Array<string>}
     * @memberof EmailScore
     */
    'confidence_factors'?: Array<string>;
    /**
     *
     * @type {ConfidenceLevel}
     * @memberof EmailScore
     */
    'confidence_level'?: ConfidenceLevel;
    /**
     * Suggested corrected email when a likely domain typo is detected
     * @type {string}
     * @memberof EmailScore
     */
    'domain_suggestion'?: string;
    /**
     *
     * @type {Freshness}
     * @memberof EmailScore
     */
    'freshness'?: Freshness;
    /**
     * Canonical form of the email after alias/plus-address normalization
     * @type {string}
     * @memberof EmailScore
     */
    'normalized_email'?: string;
    /**
     *
     * @type {PartialConfidence}
     * @memberof EmailScore
     */
    'partial_confidence'?: PartialConfidence;
    /**
     *
     * @type {Array<ReasonCode>}
     * @memberof EmailScore
     */
    'reason_codes': Array<ReasonCode>;
    /**
     *
     * @type {boolean}
     * @memberof EmailScore
     */
    'safe_to_send': boolean;
    /**
     *
     * @type {number}
     * @memberof EmailScore
     */
    'score': number;
    /**
     *
     * @type {ScoringSignals}
     * @memberof EmailScore
     */
    'signals': ScoringSignals;
    /**
     *
     * @type {SubReason}
     * @memberof EmailScore
     */
    'sub_reason': SubReason;
    /**
     *
     * @type {string}
     * @memberof EmailScore
     */
    'verified_at'?: string;
}
