/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetV1Bulk200ResponseSummary } from './get-v1-bulk200-response-summary';

/**
 *
 * @export
 * @interface GetV1Bulk200Response
 */
export interface GetV1Bulk200Response {
    /**
     *
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    'job_id': number;
    /**
     * The date and time when the bulk verification job was created.
     * @type {string}
     * @memberof GetV1Bulk200Response
     */
    'created_at': string;
    /**
     * If the bulk verification job is completed, the date and time when it was finished.
     * @type {string}
     * @memberof GetV1Bulk200Response
     */
    'finished_at'?: string;
    /**
     * The number of emails to verify in the bulk verification job.
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    'total_records': number;
    /**
     * The number of emails that have been verified at the time of the query.
     * @type {number}
     * @memberof GetV1Bulk200Response
     */
    'total_processed': number;
    /**
     *
     * @type {GetV1Bulk200ResponseSummary}
     * @memberof GetV1Bulk200Response
     */
    'summary': GetV1Bulk200ResponseSummary;
    /**
     * The status of the job, either \"Running\" or \"Completed\".
     * @type {string}
     * @memberof GetV1Bulk200Response
     */
    'job_status': GetV1Bulk200ResponseJobStatusEnum;
}

export const GetV1Bulk200ResponseJobStatusEnum = {
    Running: 'Running',
    Completed: 'Completed'
} as const;

export type GetV1Bulk200ResponseJobStatusEnum = typeof GetV1Bulk200ResponseJobStatusEnum[keyof typeof GetV1Bulk200ResponseJobStatusEnum];
