/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enumeration describing the method used to verify Hotmail B2C emails.
 * @export
 * @enum {string}
 */

export const HotmailB2CVerifMethod = {
    Smtp: 'Smtp',
    Headless: 'Headless'
} as const;

export type HotmailB2CVerifMethod = typeof HotmailB2CVerifMethod[keyof typeof HotmailB2CVerifMethod];



