/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PipelineView } from './pipeline-view';

/**
 *
 * @export
 * @interface ListPipelinesResponse
 */
export interface ListPipelinesResponse {
    /**
     *
     * @type {Array<PipelineView>}
     * @memberof ListPipelinesResponse
     */
    'pipelines': Array<PipelineView>;
    /**
     *
     * @type {number}
     * @memberof ListPipelinesResponse
     */
    'total': number;
}
