/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DiffGroup } from './diff-group';

/**
 *
 * @export
 * @interface ListDiffResponse
 */
export interface ListDiffResponse {
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'added': DiffGroup;
    /**
     *
     * @type {number}
     * @memberof ListDiffResponse
     */
    'base_list_id': number;
    /**
     *
     * @type {number}
     * @memberof ListDiffResponse
     */
    'compare_list_id': number;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'degraded': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'improved': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'newly_invalid': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'newly_risky': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'newly_safe': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'removed': DiffGroup;
    /**
     *
     * @type {DiffGroup}
     * @memberof ListDiffResponse
     */
    'unchanged': DiffGroup;
}
