/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface OutcomeInput
 */
export interface OutcomeInput {
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'campaign_id'?: string | null;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'email': string;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'event_type': string;
    /**
     *
     * @type {any}
     * @memberof OutcomeInput
     */
    'metadata'?: any;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'occurred_at'?: string | null;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'provider_event_id'?: string | null;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'provider_message_id'?: string | null;
    /**
     *
     * @type {string}
     * @memberof OutcomeInput
     */
    'source_key'?: string | null;
}
