/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PipelineSourceOneOf3
 */
export interface PipelineSourceOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'bucket': string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'path_pattern'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'prefix'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'provider': string;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'region'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf3
     */
    'type': PipelineSourceOneOf3TypeEnum;
}

export const PipelineSourceOneOf3TypeEnum = {
    Bucket: 'bucket'
} as const;

export type PipelineSourceOneOf3TypeEnum = typeof PipelineSourceOneOf3TypeEnum[keyof typeof PipelineSourceOneOf3TypeEnum];


