/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PipelineSourceOneOf
 */
export interface PipelineSourceOneOf {
    /**
     * 
     * @type {number}
     * @memberof PipelineSourceOneOf
     */
    'list_id': number;
    /**
     * 
     * @type {string}
     * @memberof PipelineSourceOneOf
     */
    'type': PipelineSourceOneOfTypeEnum;
}

export const PipelineSourceOneOfTypeEnum = {
    ListSnapshot: 'list_snapshot'
} as const;

export type PipelineSourceOneOfTypeEnum = typeof PipelineSourceOneOfTypeEnum[keyof typeof PipelineSourceOneOfTypeEnum];


