/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSourceOneOf } from './pipeline-source-one-of';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSourceOneOf1 } from './pipeline-source-one-of1';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSourceOneOf2 } from './pipeline-source-one-of2';
// May contain unused imports in some cases
// @ts-ignore
import type { PipelineSourceOneOf3 } from './pipeline-source-one-of3';

/**
 * @type PipelineSource
 * @export
 */
export type PipelineSource = { type: 'bucket' } & PipelineSourceOneOf3 | { type: 'integration' } & PipelineSourceOneOf1 | { type: 'list_snapshot' } & PipelineSourceOneOf | { type: 'push' } & PipelineSourceOneOf2;


