/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface PipelineSourceOneOf1
 */
export interface PipelineSourceOneOf1 {
    /**
     *
     * @type {string}
     * @memberof PipelineSourceOneOf1
     */
    'audience_id': string;
    /**
     *
     * @type {string}
     * @memberof PipelineSourceOneOf1
     */
    'connection_id': string;
    /**
     *
     * @type {any}
     * @memberof PipelineSourceOneOf1
     */
    'field_mapping'?: any;
    /**
     *
     * @type {string}
     * @memberof PipelineSourceOneOf1
     */
    'provider': string;
    /**
     *
     * @type {string}
     * @memberof PipelineSourceOneOf1
     */
    'type': PipelineSourceOneOf1TypeEnum;
}

export const PipelineSourceOneOf1TypeEnum = {
    Integration: 'integration'
} as const;

export type PipelineSourceOneOf1TypeEnum = typeof PipelineSourceOneOf1TypeEnum[keyof typeof PipelineSourceOneOf1TypeEnum];
