/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface ProviderEndpointView
 */
export interface ProviderEndpointView {
    /**
     *
     * @type {Array<string>}
     * @memberof ProviderEndpointView
     */
    'allowed_ips': Array<string>;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'created_at': string;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'delivery_token'?: string | null;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'endpoint_id': string;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'label': string;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'provider': string;
    /**
     *
     * @type {boolean}
     * @memberof ProviderEndpointView
     */
    'provider_configured': boolean;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'status': string;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'updated_at': string;
    /**
     *
     * @type {string}
     * @memberof ProviderEndpointView
     */
    'webhook_path': string;
}
