/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ReasonCode = {
    Deliverable: 'deliverable',
    InvalidSyntax: 'invalid_syntax',
    InvalidRecipient: 'invalid_recipient',
    SmtpUndeliverable: 'smtp_undeliverable',
    DisabledMailbox: 'disabled_mailbox',
    NoMx: 'no_mx',
    SmtpError: 'smtp_error',
    SmtpUnreachable: 'smtp_unreachable',
    CatchAll: 'catch_all',
    FullInbox: 'full_inbox',
    Disposable: 'disposable',
    RoleAccount: 'role_account',
    SpamTrap: 'spam_trap',
    UnknownDeliverability: 'unknown_deliverability',
    FreeProvider: 'free_provider',
    PossibleTypo: 'possible_typo'
} as const;

export type ReasonCode = typeof ReasonCode[keyof typeof ReasonCode];



