/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a backend/API engine for email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The hosted dashboard is a separate product surface and is not part of this repository.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RetryJobResponse
 */
export interface RetryJobResponse {
    /**
     * 
     * @type {number}
     * @memberof RetryJobResponse
     */
    'job_id': number;
    /**
     * 
     * @type {string}
     * @memberof RetryJobResponse
     */
    'status': string;
    /**
     * 
     * @type {number}
     * @memberof RetryJobResponse
     */
    'tasks_retried': number;
}

