/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher provides email verification, list hygiene, suppressions, scheduled re-verification, and pipelines. The app and API use the same host.
 *
 * The version of the OpenAPI document: 4.3.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface TenantSettingsResponse
 */
export interface TenantSettingsResponse {
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'default_policy_mode': string;
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'default_webhook_url'?: string | null;
    /**
     *
     * @type {number}
     * @memberof TenantSettingsResponse
     */
    'monthly_email_limit'?: number | null;
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'name': string;
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'period_reset_at': string;
    /**
     *
     * @type {number}
     * @memberof TenantSettingsResponse
     */
    'result_retention_days': number;
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'slug': string;
    /**
     *
     * @type {string}
     * @memberof TenantSettingsResponse
     */
    'tenant_id': string;
    /**
     *
     * @type {number}
     * @memberof TenantSettingsResponse
     */
    'used_this_period': number;
}
