/* tslint:disable */
/* eslint-disable */
/**
 * Reacher
 * ### What is Reacher?  Reacher is a robust, open-source email verification API service available as both a SaaS and self-hosted solution.
 *
 * The version of the OpenAPI document: 0.11.0
 * Contact: amaury@reacher.email
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1JobApprovalChecklist200Response
 */
export interface V1JobApprovalChecklist200Response {
    /**
     * 
     * @type {object}
     * @memberof V1JobApprovalChecklist200Response
     */
    'categories'?: object;
    /**
     * 
     * @type {number}
     * @memberof V1JobApprovalChecklist200Response
     */
    'job_id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof V1JobApprovalChecklist200Response
     */
    'ready_to_send'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V1JobApprovalChecklist200Response
     */
    'recommendation'?: string;
    /**
     * 
     * @type {object}
     * @memberof V1JobApprovalChecklist200Response
     */
    'risk_flags'?: object;
    /**
     * 
     * @type {number}
     * @memberof V1JobApprovalChecklist200Response
     */
    'safe_to_send_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1JobApprovalChecklist200Response
     */
    'safe_to_send_pct'?: number;
    /**
     * 
     * @type {number}
     * @memberof V1JobApprovalChecklist200Response
     */
    'total_records'?: number;
}

